  UPDATE GAS_PARAMETROS_CIERRE
  SET ESTADO = 'I'  --ABRIR
  WHERE ESTADO = 'A' --CERRADO
 AND PLATAFORMA IN (
     SELECT ID  FROM GAS_PLATAFORMAS
     WHERE AUTO_CIERRE = 1 AND ACTIVO IN ('KU MALOOB ZAAP','AYATSIL-TEKEL') AND BAJA IS NULL) 
     AND FECHA_CONTABLE BETWEEN TO_DATE(:FECHA_INICIAL,'DD/MM/YYYY')-1 AND TO_DATE(:FECHA_FINAL,'DD/MM/YYYY')-1