-- Aceite Producido de los campos de Abkatun Pol Chuc /////////////////


SELECT FEC_PROD,ACTIVO,CAMPO,PROD_ACE
FROM
(select d.fecha_contable as fec_prod,'ABKATUN POOL CHUC' AS ACTIVO, c.campo AS CAMPO,d.valor_numerico as PROD_ACE from 
  (SELECT a.id_parametros, a.fecha_real, a.id_hora, a.plataforma,
       a.fecha_contable, a.valor_numerico
  FROM gas_parametros_valores a  
  where a.plataforma=272
  and a.id_parametros in (509,505,499,513,507,519,515,517,503,1378,1386,511)
  and a.fecha_real + 1 BETWEEN TO_DATE(:FECHA_INI, 'DD/MM/YYYY') AND TO_DATE(:FECHA_FIN, 'DD/MM/YYYY')
  and a.id_hora in (24,49,72))d,

  (SELECT A.ID_PARAMETROS,UPPER( B.DESCRIPCION ) CAMPO,a.padre
   FROM GAS_C_PARAMETROS A, GAS_C_PARAMETROS B
   WHERE A.PADRE = B.ID_PARAMETROS
   AND A.ID_PARAMETROS IN(509,505,499,513,507,519,515,517,503,1378,1386,511) order by 3)c
                    
where c.id_parametros=d.id_parametros(+)

UNION ALL

-- ACEITE PRODUCIDO LITORAL TABASCO ACEITE

SELECT DATE_STAMP AS FEC_PROD,'LITORAL TABASCO' AS ACTIVO,A.CAMPO AS CAMPO,round(A.ACEITE_NETA_BPD,0) AS PROD_ACE
           
FROM REP_HISTO_OIL_GAS_PROM2 A
WHERE  A.date_stamp + 1 BETWEEN TO_DATE(:FECHA_INI, 'DD/MM/YYYY') AND TO_DATE(:FECHA_FIN, 'DD/MM/YYYY'))

WHERE CAMPO IN ('ALUX')














--COMBO DE CAMPOS


select campo,texto from
--CAMPOS ACEITE ABK
(select distinct '''' || c.campo || '''' AS campo, c.campo as texto, 'ABKATUN POOL CHUC' as activo from 
  (SELECT a.id_parametros, a.fecha_real, a.id_hora, a.plataforma,
       a.fecha_contable, a.valor_numerico
  FROM gas_parametros_valores a  
  where a.plataforma=272
  and a.id_parametros in (509,505,499,513,507,519,515,517,503,1378,1386,511)
  and a.fecha_real + 1 BETWEEN TO_DATE(:FECHA_INI, 'DD/MM/YYYY') AND TO_DATE(:FECHA_FIN, 'DD/MM/YYYY')
  and a.id_hora in (24,49,72))d,

  (SELECT A.ID_PARAMETROS,UPPER( B.DESCRIPCION ) CAMPO,a.padre
   FROM GAS_C_PARAMETROS A, GAS_C_PARAMETROS B
   WHERE A.PADRE = B.ID_PARAMETROS
   AND A.ID_PARAMETROS IN(509,505,499,513,507,519,515,517,503,1378,1386,511) order by 3)c
                    
where c.id_parametros=d.id_parametros(+)

UNION ALL

--CAMPOS ACEITE LITORAL

select distinct '''' || campo || '''' AS campo, campo as texto, 'LITORAL TABASCO' as activo
from REP_HISTO_OIL_GAS_PROM2
where date_stamp + 1 BETWEEN TO_DATE(:FECHA_INI, 'DD/MM/YYYY') AND TO_DATE(:FECHA_FIN, 'DD/MM/YYYY')
and campo not in 'Gran Total' 
order by 2)
where activo in ('LITORAL')






--OBSERVACIONES


SELECT FECHA,VOL ||' '|| OBS AS OBS
FROM
--OBSERVACIONES ABK
(

SELECT '1',FECHA,'['||VOL||']' AS VOL,OBS,ACTIVO FROM
(
SELECT 
TO_DATE(:FECHA,'DD/MM/YYYY') AS FECHA,
DECODE(MSO_ACE_VALOR_NUM(546,TO_CHAR(to_date(:FECHA, 'DD-MM-YYYY')+1, 'dd/MM/YYYY'),MA_ACEITE_ID_HORA(TO_CHAR(to_date(:FECHA, 'DD-MM-YYYY')+1, 'dd/MM/YYYY'), '05:00') , 272,''),0,NULL,TO_CHAR(MSO_ACE_VALOR_NUM(546,TO_CHAR(to_date(:FECHA, 'DD-MM-YYYY')+1, 'dd/MM/YYYY'),MA_ACEITE_ID_HORA(TO_CHAR(to_date(:FECHA, 'DD-MM-YYYY')+1, 'dd/MM/YYYY'), '05:00') , 272,''),'99,999')|| ' BPD.') AS VOL, MSO_ACE_VALOR_CAD(397,TO_CHAR(to_date(:FECHA, 'DD-MM-YYYY')+1, 'dd/MM/YYYY'),MA_ACEITE_ID_HORA(TO_CHAR(to_date(:FECHA, 'DD-MM-YYYY')+1, 'dd/MM/YYYY'), '05:00') , 272,'') AS OBS
,'ABKATUN POOL CHUC' AS ACTIVO
FROM DUAL
UNION
SELECT
TO_DATE(:FECHA,'DD/MM/YYYY') AS FECHA,
DECODE(MSO_ACE_VALOR_NUM(548,TO_CHAR(to_date(:FECHA, 'DD-MM-YYYY')+1, 'dd/MM/YYYY'),MA_ACEITE_ID_HORA(TO_CHAR(to_date(:FECHA, 'DD-MM-YYYY')+1, 'dd/MM/YYYY'), '05:00') , 272,''),0,NULL,TO_CHAR(MSO_ACE_VALOR_NUM(548,TO_CHAR(to_date(:FECHA, 'DD-MM-YYYY')+1, 'dd/MM/YYYY'),MA_ACEITE_ID_HORA(TO_CHAR(to_date(:FECHA, 'DD-MM-YYYY')+1, 'dd/MM/YYYY'), '05:00') , 272,''),'99,999')||' BPD.'),MSO_ACE_VALOR_CAD(400,TO_CHAR(to_date(:FECHA, 'DD-MM-YYYY')+1, 'dd/MM/YYYY'),MA_ACEITE_ID_HORA(TO_CHAR(to_date(:FECHA, 'DD-MM-YYYY')+1, 'dd/MM/YYYY'), '05:00')  , 272,'') AS OBS
,'ABKATUN POOL CHUC' AS ACTIVO
FROM DUAL
UNION
SELECT
TO_DATE(:FECHA,'DD/MM/YYYY') AS FECHA,
DECODE(MSO_ACE_VALOR_NUM(559,TO_CHAR(to_date(:FECHA, 'DD-MM-YYYY')+1, 'dd/MM/YYYY'),MA_ACEITE_ID_HORA(TO_CHAR(to_date(:FECHA, 'DD-MM-YYYY')+1, 'dd/MM/YYYY'), '05:00') , 272,''),0,NULL,TO_CHAR(MSO_ACE_VALOR_NUM(559,TO_CHAR(to_date(:FECHA, 'DD-MM-YYYY')+1, 'dd/MM/YYYY'),MA_ACEITE_ID_HORA(TO_CHAR(to_date(:FECHA, 'DD-MM-YYYY')+1, 'dd/MM/YYYY'), '05:00') , 272,''),'99,999')||' BPD.'),MSO_ACE_VALOR_CAD(402,TO_CHAR(to_date(:FECHA, 'DD-MM-YYYY')+1, 'dd/MM/YYYY'),MA_ACEITE_ID_HORA(TO_CHAR(to_date(:FECHA, 'DD-MM-YYYY')+1, 'dd/MM/YYYY'), '05:00') , 272,'') AS OBS
,'ABKATUN POOL CHUC' AS ACTIVO
FROM DUAL
UNION
SELECT
TO_DATE(:FECHA,'DD/MM/YYYY') AS FECHA,
DECODE(MSO_ACE_VALOR_NUM(554,TO_CHAR(to_date(:FECHA, 'DD-MM-YYYY')+1, 'dd/MM/YYYY'),MA_ACEITE_ID_HORA(TO_CHAR(to_date(:FECHA, 'DD-MM-YYYY')+1, 'dd/MM/YYYY'), '05:00') , 272,''),0,NULL,TO_CHAR(MSO_ACE_VALOR_NUM(554,TO_CHAR(to_date(:FECHA, 'DD-MM-YYYY')+1, 'dd/MM/YYYY'),MA_ACEITE_ID_HORA(TO_CHAR(to_date(:FECHA, 'DD-MM-YYYY')+1, 'dd/MM/YYYY'), '05:00') , 272,''),'99,999')||' BPD.'),MSO_ACE_VALOR_CAD(404,TO_CHAR(to_date(:FECHA, 'DD-MM-YYYY')+1, 'dd/MM/YYYY'),MA_ACEITE_ID_HORA(TO_CHAR(to_date(:FECHA, 'DD-MM-YYYY')+1, 'dd/MM/YYYY'), '05:00')  , 272,'') AS OBS
,'ABKATUN POOL CHUC' AS ACTIVO
FROM DUAL
UNION
SELECT
TO_DATE(:FECHA,'DD/MM/YYYY') AS FECHA,
DECODE(MSO_ACE_VALOR_NUM(553,TO_CHAR(to_date(:FECHA, 'DD-MM-YYYY')+1, 'dd/MM/YYYY'),MA_ACEITE_ID_HORA(TO_CHAR(to_date(:FECHA, 'DD-MM-YYYY')+1, 'dd/MM/YYYY'), '05:00') , 272,''),0,NULL,TO_CHAR(MSO_ACE_VALOR_NUM(553,TO_CHAR(to_date(:FECHA, 'DD-MM-YYYY')+1, 'dd/MM/YYYY'),MA_ACEITE_ID_HORA(TO_CHAR(to_date(:FECHA, 'DD-MM-YYYY')+1, 'dd/MM/YYYY'), '05:00') , 272,''),'99,999')|| ' BPD.'),MSO_ACE_VALOR_CAD(406,TO_CHAR(to_date(:FECHA, 'DD-MM-YYYY')+1, 'dd/MM/YYYY'),MA_ACEITE_ID_HORA(TO_CHAR(to_date(:FECHA, 'DD-MM-YYYY')+1, 'dd/MM/YYYY'), '05:00')  , 272,'') AS OBS
,'ABKATUN POOL CHUC' AS ACTIVO
FROM DUAL
UNION
SELECT
TO_DATE(:FECHA,'DD/MM/YYYY') AS FECHA,
DECODE(MSO_ACE_VALOR_NUM(555,TO_CHAR(to_date(:FECHA, 'DD-MM-YYYY')+1, 'dd/MM/YYYY'),MA_ACEITE_ID_HORA(TO_CHAR(to_date(:FECHA, 'DD-MM-YYYY')+1, 'dd/MM/YYYY'), '05:00') , 272,''),0,NULL,TO_CHAR(MSO_ACE_VALOR_NUM(555,TO_CHAR(to_date(:FECHA, 'DD-MM-YYYY')+1, 'dd/MM/YYYY'),MA_ACEITE_ID_HORA(TO_CHAR(to_date(:FECHA, 'DD-MM-YYYY')+1, 'dd/MM/YYYY'), '05:00') , 272,''),'99,999')||' BPD.' ),MSO_ACE_VALOR_CAD(416,TO_CHAR(to_date(:FECHA, 'DD-MM-YYYY')+1, 'dd/MM/YYYY'),MA_ACEITE_ID_HORA(TO_CHAR(to_date(:FECHA, 'DD-MM-YYYY')+1, 'dd/MM/YYYY'), '05:00')  , 272,'') AS OBS
,'ABKATUN POOL CHUC' AS ACTIVO
FROM DUAL
UNION
SELECT
TO_DATE(:FECHA,'DD/MM/YYYY') AS FECHA,
DECODE(MSO_ACE_VALOR_NUM(547,TO_CHAR(to_date(:FECHA, 'DD-MM-YYYY')+1, 'dd/MM/YYYY'),MA_ACEITE_ID_HORA(TO_CHAR(to_date(:FECHA, 'DD-MM-YYYY')+1, 'dd/MM/YYYY'), '05:00') , 272,''),0,NULL,TO_CHAR(MSO_ACE_VALOR_NUM(547,TO_CHAR(to_date(:FECHA, 'DD-MM-YYYY')+1, 'dd/MM/YYYY'),MA_ACEITE_ID_HORA(TO_CHAR(to_date(:FECHA, 'DD-MM-YYYY')+1, 'dd/MM/YYYY'), '05:00') , 272,''),'99,999')||' BPD.'),MSO_ACE_VALOR_CAD(408,TO_CHAR(to_date(:FECHA, 'DD-MM-YYYY')+1, 'dd/MM/YYYY'),MA_ACEITE_ID_HORA(TO_CHAR(to_date(:FECHA, 'DD-MM-YYYY')+1, 'dd/MM/YYYY'), '05:00')  , 272,'') AS OBS
,'ABKATUN POOL CHUC' AS ACTIVO
FROM DUAL
UNION
SELECT
TO_DATE(:FECHA,'DD/MM/YYYY') AS FECHA,
DECODE(MSO_ACE_VALOR_NUM(549,TO_CHAR(to_date(:FECHA, 'DD-MM-YYYY')+1, 'dd/MM/YYYY'),MA_ACEITE_ID_HORA(TO_CHAR(to_date(:FECHA, 'DD-MM-YYYY')+1, 'dd/MM/YYYY'), '05:00') , 272,''),0,NULL,TO_CHAR(MSO_ACE_VALOR_NUM(549,TO_CHAR(to_date(:FECHA, 'DD-MM-YYYY')+1, 'dd/MM/YYYY'),MA_ACEITE_ID_HORA(TO_CHAR(to_date(:FECHA, 'DD-MM-YYYY')+1, 'dd/MM/YYYY'), '05:00') , 272,''),'99,999')|| ' BPD. '),MSO_ACE_VALOR_CAD(410,TO_CHAR(to_date(:FECHA, 'DD-MM-YYYY')+1, 'dd/MM/YYYY'),MA_ACEITE_ID_HORA(TO_CHAR(to_date(:FECHA, 'DD-MM-YYYY')+1, 'dd/MM/YYYY'), '05:00')  , 272,'') AS OBS
,'ABKATUN POOL CHUC' AS ACTIVO
FROM DUAL
UNION
SELECT
TO_DATE(:FECHA,'DD/MM/YYYY') AS FECHA,
DECODE(MSO_ACE_VALOR_NUM(557,TO_CHAR(to_date(:FECHA, 'DD-MM-YYYY')+1, 'dd/MM/YYYY'),MA_ACEITE_ID_HORA(TO_CHAR(to_date(:FECHA, 'DD-MM-YYYY')+1, 'dd/MM/YYYY'), '05:00') , 272,''),0,NULL,TO_CHAR(MSO_ACE_VALOR_NUM(557,TO_CHAR(to_date(:FECHA, 'DD-MM-YYYY')+1, 'dd/MM/YYYY'),MA_ACEITE_ID_HORA(TO_CHAR(to_date(:FECHA, 'DD-MM-YYYY')+1, 'dd/MM/YYYY'), '05:00') , 272,''),'99,999')||' BPD.'),MSO_ACE_VALOR_CAD(413,TO_CHAR(to_date(:FECHA, 'DD-MM-YYYY')+1, 'dd/MM/YYYY'),MA_ACEITE_ID_HORA(TO_CHAR(to_date(:FECHA, 'DD-MM-YYYY')+1, 'dd/MM/YYYY'), '05:00')  , 272,'') AS OBS
,'ABKATUN POOL CHUC' AS ACTIVO
FROM DUAL
UNION
SELECT
TO_DATE(:FECHA,'DD/MM/YYYY') AS FECHA,
DECODE(MSO_ACE_VALOR_NUM(551,TO_CHAR(to_date(:FECHA, 'DD-MM-YYYY')+1, 'dd/MM/YYYY'),MA_ACEITE_ID_HORA(TO_CHAR(to_date(:FECHA, 'DD-MM-YYYY')+1, 'dd/MM/YYYY'), '05:00') , 272,''),0,NULL,TO_CHAR(MSO_ACE_VALOR_NUM(551,TO_CHAR(to_date(:FECHA, 'DD-MM-YYYY')+1, 'dd/MM/YYYY'),MA_ACEITE_ID_HORA(TO_CHAR(to_date(:FECHA, 'DD-MM-YYYY')+1, 'dd/MM/YYYY'), '05:00') , 272,''),'99,999')||' BPD.'),MSO_ACE_VALOR_CAD(419,TO_CHAR(to_date(:FECHA, 'DD-MM-YYYY')+1, 'dd/MM/YYYY'),MA_ACEITE_ID_HORA(TO_CHAR(to_date(:FECHA, 'DD-MM-YYYY')+1, 'dd/MM/YYYY'), '05:00')  , 272,'') AS OBS
,'ABKATUN POOL CHUC' AS ACTIVO
FROM DUAL
UNION
SELECT
TO_DATE(:FECHA,'DD/MM/YYYY') AS FECHA,
DECODE(MSO_ACE_VALOR_NUM(1380,TO_CHAR(to_date(:FECHA, 'DD-MM-YYYY')+1, 'dd/MM/YYYY'),MA_ACEITE_ID_HORA(TO_CHAR(to_date(:FECHA, 'DD-MM-YYYY')+1, 'dd/MM/YYYY'), '05:00') , 272,''),0,NULL,TO_CHAR(MSO_ACE_VALOR_NUM(1380,TO_CHAR(to_date(:FECHA, 'DD-MM-YYYY')+1, 'dd/MM/YYYY'),MA_ACEITE_ID_HORA(TO_CHAR(to_date(:FECHA, 'DD-MM-YYYY')+1, 'dd/MM/YYYY'), '05:00') , 272,''),'99,999')||' BPD.'),MSO_ACE_VALOR_CAD(1403,TO_CHAR(to_date(:FECHA, 'DD-MM-YYYY')+1, 'dd/MM/YYYY'),MA_ACEITE_ID_HORA(TO_CHAR(to_date(:FECHA, 'DD-MM-YYYY')+1, 'dd/MM/YYYY'), '05:00')  , 272,'') AS OBS
,'ABKATUN POOL CHUC' AS ACTIVO
FROM DUAL
UNION
SELECT
TO_DATE(:FECHA,'DD/MM/YYYY') AS FECHA,
DECODE(MSO_ACE_VALOR_NUM(1382,TO_CHAR(to_date(:FECHA, 'DD-MM-YYYY')+1, 'dd/MM/YYYY'),MA_ACEITE_ID_HORA(TO_CHAR(to_date(:FECHA, 'DD-MM-YYYY')+1, 'dd/MM/YYYY'), '05:00') , 272,''),0,NULL,TO_CHAR(MSO_ACE_VALOR_NUM(1382,TO_CHAR(to_date(:FECHA, 'DD-MM-YYYY')+1, 'dd/MM/YYYY'),MA_ACEITE_ID_HORA(TO_CHAR(to_date(:FECHA, 'DD-MM-YYYY')+1, 'dd/MM/YYYY'), '05:00') , 272,''),'99,999')|| ' BPD.'),MSO_ACE_VALOR_CAD(1406,TO_CHAR(to_date(:FECHA, 'DD-MM-YYYY')+1, 'dd/MM/YYYY'),MA_ACEITE_ID_HORA(TO_CHAR(to_date(:FECHA, 'DD-MM-YYYY')+1, 'dd/MM/YYYY'), '05:00')  , 272,'') AS OBS
,'ABKATUN POOL CHUC' AS ACTIVO
FROM DUAL)
WHERE VOL IS NOT NULL

UNION ALL


--LITORAL TABASCO

SELECT ORDEN,FECHA,VOL, OBS,ACTIVO FROM
(
(SELECT '1' AS ORDEN,MAX(DATE_STAMP)FECHA,DECODE(ROUND(SUM(OILDIFFERENCE),0),NULL,NULL,'['||TO_CHAR(ROUND(SUM(OILDIFFERENCE),0),'99,999')||' BPD.]') AS VOL,'Variación de la producción por diferencias de medición de complejos.' AS OBS, 'LITORAL TABASCO' AS ACTIVO  
FROM REP_DIST_TEMP_VAR_PROMSO   
WHERE DATE_STAMP = TO_DATE(:FECHA,'DD/MM/YYYY'))

UNION 

(SELECT '1' AS ORDEN,MAX(DATE_STAMP)FECHA,DECODE(ROUND(SUM(OILWATERDIFF),0),NULL,NULL,'['||TO_CHAR(ROUND(SUM(OILWATERDIFF),0),'99,999')||' BPD.]'),'Variación de la producción por porcentaje de agua.', 'LITORAL TABASCO' AS ACTIVO
FROM REP_DIST_TEMP_VAR_PROMSO   
WHERE DATE_STAMP = TO_DATE(:FECHA,'DD/MM/YYYY'))

UNION

(SELECT '1' AS ORDEN,MAX(DATE_STAMP)FECHA, DECODE(ROUND(SUM(OILPRESSDIFF),0),NULL,NULL,'['||TO_CHAR(ROUND(SUM(OILPRESSDIFF),0),'99,999')||' BPD.]') ,'Variación de la producción por presión en la cabeza.', 'LITORAL TABASCO' AS ACTIVO
FROM REP_DIST_TEMP_VAR_PROMSO   
WHERE DATE_STAMP = TO_DATE(:FECHA,'DD/MM/YYYY'))

UNION

(SELECT '1' as ORDEN,MAX(DATE_STAMP)FECHA,DECODE(ROUND(SUM(OILPOTENTIAL),0),NULL,NULL,'['||TO_CHAR(ROUND(SUM(OILPOTENTIAL),0),'99,999')||' BPD.]'),'Variación por producción 24 horas.', 'LITORAL TABASCO' AS ACTIVO
FROM REP_DIST_TEMP_VAR_PROMSO   
WHERE DATE_STAMP = TO_DATE(:FECHA,'DD/MM/YYYY'))
)
WHERE VOL IS NOT NULL


UNION

SELECT '2' AS ORDEN,FECHA DATE_STAMP,DECODE(OIL_BBL,null,null,'['|| OIL_BBL ||' MMCPD.]') as volumen,POZO||'     '|| CONCEPTO  as OBS, 'LITORAL TABASCO' AS ACTIVO
FROM planeacion_mov_PROMSO 
WHERE FECHA = TO_DATE(:FECHA,'DD/MM/YYYY')
ORDER BY 1


)
WHERE ACTIVO IN (:ACTIVO)


















--TOTAL DIA ACTIVO


SELECT round(TOTAL,0) as total
FROM

(
select d.fecha_contable as fec_prod,'ABKATUN POOL CHUC' AS ACTIVO,SUM(d.valor_numerico) as TOTAL from 
  (SELECT a.id_parametros, a.fecha_real, a.id_hora, a.plataforma,
       a.fecha_contable, a.valor_numerico
  FROM gas_parametros_valores a  
  where a.plataforma=272
  and a.id_parametros in (509,505,499,513,507,519,515,517,503,1378,1386,511)
  and a.fecha_real = TO_DATE(:FECHA, 'DD/MM/YYYY')+1
  and a.id_hora in (24,49,72))d,

  (SELECT A.ID_PARAMETROS,UPPER( B.DESCRIPCION ) CAMPO,a.padre
   FROM GAS_C_PARAMETROS A, GAS_C_PARAMETROS B
   WHERE A.PADRE = B.ID_PARAMETROS
   AND A.ID_PARAMETROS IN(509,505,499,513,507,519,515,517,503,1378,1386,511) order by 3)c
                    
where c.id_parametros=d.id_parametros(+)
GROUP BY d.fecha_contable,'ABKATUN POOL CHUC' 

UNION ALL

-- ACEITE PRODUCIDO LITORAL TABASCO ACEITE

SELECT DATE_STAMP AS FEC_PROD,'LITORAL TABASCO' AS ACTIVO,SUM(round(A.ACEITE_NETA_BPD,0)) AS TOTAL
           
FROM REP_HISTO_OIL_GAS_PROM2 A
WHERE  A.date_stamp = TO_DATE(:FECHA, 'DD/MM/YYYY')
AND a.campo not in 'Gran Total' 
GROUP BY DATE_STAMP,'LITORAL TABASCO' 
)
WHERE ACTIVO IN (:ACTIVO)


