
SELECT CAMPO.ACTIVO,CAMPO.CAMPO AS CAMPO,SUM(CAMPO.PROD_ACE) AS PRODUCCIONACE,SUM(CAMPO.PROD_GAS) AS PRODUCCIONGAS,
TOTALAIC.TOTACE AS ACEITEAIC,TOTALAIC.TOTGAS AS GASAIC, TOTALKMZ.TOTACE AS ACEITEKMZ, TOTALKMZ.TOTGAS AS GASKMZ,
TOTALAICLIG.TOTACE AS ACEITEAICLIG,TOTALAICLIG.TOTGAS AS GASAICLIG,TOTALKMZLIG.TOTACE AS ACEITEKMZLIG, TOTALKMZLIG.TOTGAS AS GASKMZLIG

FROM
(
SELECT FEC_PROD,
CASE WHEN PROYECTO='EK BALAM' THEN 'CANTARELL'
WHEN PROYECTO='CANTARELL' THEN PROYECTO
WHEN PROYECTO='KU MALOOB ZAAP' THEN PROYECTO END AS ACTIVO,

 CAMPO, TIPO_PROD, PROD_ACE, PROD_GAS

FROM HIST_PROD

WHERE fec_prod = TO_DATE(:FECHA, 'DD/MM/YYYY')-1
and tipo_prod in ('PESADO','LIGERO')
order by fec_prod

)CAMPO,
(

SELECT SUM(TOTAL.PROD_ACE) AS TOTACE,SUM(TOTAL.PROD_GAS) AS TOTGAS
FROM
(SELECT FEC_PROD,
CASE WHEN PROYECTO='EK BALAM' THEN 'CANTARELL'
WHEN PROYECTO='CANTARELL' THEN PROYECTO
WHEN PROYECTO='KU MALOOB ZAAP' THEN PROYECTO END AS ACTIVO,

 CAMPO, TIPO_PROD, PROD_ACE, PROD_GAS

FROM HIST_PROD

WHERE fec_prod = TO_DATE(:FECHA, 'DD/MM/YYYY')-1
and tipo_prod in ('PESADO')
order by fec_prod)TOTAL
WHERE ACTIVO = 'CANTARELL'


)TOTALAIC,

(

SELECT 
DECODE(SUM(TOTAL.PROD_ACE),null,0,SUM(TOTAL.PROD_ACE)) AS TOTACE, DECODE(SUM(TOTAL.PROD_GAS),NULL,0,SUM(TOTAL.PROD_GAS)) AS TOTGAS
FROM
(

SELECT FEC_PROD,
CASE WHEN PROYECTO='EK BALAM' THEN 'CANTARELL'
WHEN PROYECTO='CANTARELL' THEN PROYECTO
WHEN PROYECTO='KU MALOOB ZAAP' THEN PROYECTO END AS ACTIVO,

 CAMPO, TIPO_PROD, PROD_ACE, PROD_GAS

FROM HIST_PROD

WHERE fec_prod = TO_DATE(:FECHA, 'DD/MM/YYYY')-1
and tipo_prod in ('PESADO')

order by fec_prod)TOTAL

WHERE ACTIVO = 'KU MALOOB ZAAP'

)TOTALKMZ,

(

SELECT SUM(TOTAL.PROD_ACE) AS TOTACE,SUM(TOTAL.PROD_GAS) AS TOTGAS
FROM
(SELECT FEC_PROD,
CASE WHEN PROYECTO='EK BALAM' THEN 'CANTARELL'
WHEN PROYECTO='CANTARELL' THEN PROYECTO
WHEN PROYECTO='KU MALOOB ZAAP' THEN PROYECTO END AS ACTIVO,

 CAMPO, TIPO_PROD, PROD_ACE, PROD_GAS

FROM HIST_PROD

WHERE fec_prod = TO_DATE(:FECHA, 'DD/MM/YYYY')-1
and tipo_prod in ('LIGERO')
order by fec_prod)TOTAL
WHERE ACTIVO = 'CANTARELL'


)TOTALAICLIG,

(

SELECT 
DECODE(SUM(TOTAL.PROD_ACE),null,0,SUM(TOTAL.PROD_ACE)) AS TOTACE, DECODE(SUM(TOTAL.PROD_GAS),NULL,0,SUM(TOTAL.PROD_GAS)) AS TOTGAS
FROM
(

SELECT FEC_PROD,
CASE WHEN PROYECTO='EK BALAM' THEN 'CANTARELL'
WHEN PROYECTO='CANTARELL' THEN PROYECTO
WHEN PROYECTO='KU MALOOB ZAAP' THEN PROYECTO END AS ACTIVO,

 CAMPO, TIPO_PROD, PROD_ACE, PROD_GAS

FROM HIST_PROD

WHERE fec_prod = TO_DATE(:FECHA, 'DD/MM/YYYY')-1
and tipo_prod in ('LIGERO')

order by fec_prod)TOTAL

WHERE ACTIVO = 'KU MALOOB ZAAP'

)TOTALKMZLIG



GROUP BY CAMPO.ACTIVO,CAMPO.CAMPO,TOTALAIC.TOTACE,TOTALAIC.TOTGAS, TOTALKMZ.TOTACE, TOTALKMZ.TOTGAS,
TOTALAICLIG.TOTACE,TOTALAICLIG.TOTGAS, TOTALKMZLIG.TOTACE, TOTALKMZLIG.TOTGAS 
ORDER BY CAMPO.ACTIVO