INSERT INTO GAS_PARAMETROS_CIERRE
(ID_CIERRE,FECHA_CONTABLE,PLATAFORMA,USR_CREACION,FEC_CREACION,ESTADO)
(SELECT CIERRE.ID_CIERRE+ROWNUM AS id_cierre, FECHA.FECHA,PLAT.ID,'PEMEX\331033',TO_DATE(TO_CHAR(SYSDATE,'DD/MM/YYYY'),'DD/MM/YYYY'),'A'
FROM 
(SELECT FECHA
FROM (
SELECT LEVEL,TO_DATE(:FECHA_INI,'DD/MM/YYYY')+LEVEL-1 FECHA
FROM DUAL
CONNECT BY LEVEL BETWEEN 1 AND TO_NUMBER(TO_DATE(:FECHA_FIN,'DD/MM/YYYY') - TO_DATE(:FECHA_INI,'DD/MM/YYYY'))+1 )
ORDER BY FECHA)FECHA,
   (SELECT ID  FROM GAS_PLATAFORMAS
     WHERE AUTO_CIERRE = 1 AND ACTIVO IN ('KU MALOOB ZAAP','AYATSIL-TEKEL') AND BAJA IS NULL AND TIPO_INST IN ('POZO','TAB_POZO','PROD_BASE'))PLAT,
     (SELECT MAX(ID_CIERRE)+1 ID_CIERRE FROM GAS_PARAMETROS_CIERRE)CIERRE
     

   
