

/*CONSULTA POR DIA*/

(SELECT
 MAX(DECODE(ACTIVO, 'KU MALOOB ZAAP', POA, NULL))AS "KMZ",
 MAX(DECODE(ACTIVO, 'CANTARELL', POA, NULL))AS "CANTARELL"
FROM

(SELECT ACTIVO,DIA, ROUND(SUM(POM/1000),2)AS POM, ROUND(SUM(POA/1000),2)AS POA,ROUND(SUM(POT1/1000),2)AS POT1 FROM programas_gas_rmne
WHERE PRODUCTO='ACEITE' AND DIA= TRUNC(:FECHA,'MM')
GROUP BY ACTIVO,DIA
)

UNION ALL

SELECT
 MAX(DECODE(ACTIVO, 'KU MALOOB ZAAP', POT1, NULL))AS "KMZ",
 MAX(DECODE(ACTIVO, 'CANTARELL', POT1, NULL))AS "CANTARELL"
FROM

(SELECT ACTIVO,DIA, ROUND(SUM(POM/1000),2)AS POM, ROUND(SUM(POA/1000),2)AS POA,ROUND(SUM(POT1/1000),2)AS POT1 FROM programas_gas_rmne
WHERE PRODUCTO='ACEITE' AND DIA= TRUNC(:FECHA,'MM')
GROUP BY ACTIVO,DIA)

UNION ALL

SELECT
 MAX(DECODE(ACTIVO, 'KU MALOOB ZAAP', POM, NULL))AS "KMZ",
 MAX(DECODE(ACTIVO, 'CANTARELL', POM, NULL))AS "CANTARELL"
FROM

(SELECT ACTIVO,DIA, ROUND(SUM(POM/1000),2)AS POM, ROUND(SUM(POA/1000),2)AS POA,ROUND(SUM(POT1/1000),2)AS POT1 FROM programas_gas_rmne
WHERE PRODUCTO='ACEITE' AND DIA= TRUNC(:FECHA,'MM')
GROUP BY ACTIVO,DIA))


UNION ALL

/*SUMA DE PROMEDIOS*/

(SELECT ROUND(SUM(KMZ),2),ROUND(SUM(CANTARELL),2)

FROM

(SELECT /*PROMEDIO POA*/
 MAX(DECODE(ACTIVO, 'KU MALOOB ZAAP', PPOA, NULL))AS "KMZ",
 MAX(DECODE(ACTIVO, 'CANTARELL', PPOA, NULL))AS "CANTARELL"
FROM

(SELECT ACTIVO, AVG(POM) AS PPOM, AVG(POA) AS PPOA, AVG(POT1) AS PPOT1
FROM 

(SELECT ACTIVO,DIA, ROUND(SUM(POM/1000),2)AS POM, ROUND(SUM(POA/1000),2)AS POA,ROUND(SUM(POT1/1000),2)AS POT1 FROM programas_gas_rmne
WHERE PRODUCTO='ACEITE' AND DIA BETWEEN TRUNC(:FECHA,'year') AND TRUNC(:FECHA,'MM')
GROUP BY ACTIVO,DIA)
GROUP BY ACTIVO)

UNION ALL

SELECT /*PROMEDIO POT-1*/
 MAX(DECODE(ACTIVO, 'KU MALOOB ZAAP', PPOT1, NULL))AS "KMZ",
 MAX(DECODE(ACTIVO, 'CANTARELL', PPOT1, NULL))AS "CANTARELL"
FROM

(SELECT ACTIVO, AVG(POM) AS PPOM, AVG(POA) AS PPOA, AVG(POT1) AS PPOT1
FROM 

(SELECT ACTIVO,DIA, ROUND(SUM(POM/1000),2)AS POM, ROUND(SUM(POA/1000),2)AS POA,ROUND(SUM(POT1/1000),2)AS POT1 FROM programas_gas_rmne
WHERE PRODUCTO='ACEITE' AND DIA BETWEEN TRUNC(:FECHA,'year') AND TRUNC(:FECHA,'MM')
GROUP BY ACTIVO,DIA)
GROUP BY ACTIVO)

UNION ALL

SELECT /*PROMEDIO POM*/
 MAX(DECODE(ACTIVO, 'KU MALOOB ZAAP', PPOM, NULL))AS "KMZ",
 MAX(DECODE(ACTIVO, 'CANTARELL', PPOM, NULL))AS "CANTARELL"
FROM

(SELECT ACTIVO, AVG(POM) AS PPOM, AVG(POA) AS PPOA, AVG(POT1) AS PPOT1
FROM 

(SELECT ACTIVO,DIA, ROUND(SUM(POM/1000),2)AS POM, ROUND(SUM(POA/1000),2)AS POA,ROUND(SUM(POT1/1000),2)AS POT1 FROM programas_gas_rmne
WHERE PRODUCTO='ACEITE' AND DIA BETWEEN TRUNC(:FECHA,'year') AND TRUNC(:FECHA,'MM')
GROUP BY ACTIVO,DIA)
GROUP BY ACTIVO)))