/* GAS ZONA DE TRANSICION */

WITH FECHAS AS
(SELECT
   TO_DATE(:FECHA_INI_SEMANA, 'DD/MM/YYYY') - 1 As FEC_INI_SEMANA,
   TO_DATE(:FECHA_FIN_SEMANA, 'DD/MM/YYYY') - 1 As FEC_FIN_SEMANA,
   ADD_MONTHS(TRUNC(
          TO_DATE(:FECHA_FIN_SEMANA, 'DD/MM/YYYY') - 1
     , 'YYYY'),-12) As FEC_INI_ANIO_ANT,
    TRUNC(
         TO_DATE(:FECHA_FIN_SEMANA, 'DD/MM/YYYY') - 1
     , 'YYYY') As FEC_INI_ANIO_ACT
FROM DUAL)

SELECT
    FECHAS.FECHA_CONTABLE, 
    FECHAS.FECHA_CONTABLE + 1 As FECHA_REAL,
    GAS_ZT_REAL.GAS_ZT As GAS_ZT_REAL, 
    GAS_ZT_PROG.GAS_ZT As GAS_ZT_PROG,
    GAS_ZT_PROG.GAS_POT As GAS_ZT_POT,
    FECHAS_SEM.FEC_INI_SEMANA, 
    FECHAS_SEM.FEC_FIN_SEMANA, 
    FECHAS_SEM.FEC_INI_ANIO_ANT,
    FECHAS_SEM.FEC_INI_ANIO_ACT,
    CASE
       WHEN FECHAS_SEM.FEC_FIN_SEMANA = LAST_DAY(FECHAS_SEM.FEC_FIN_SEMANA) THEN FECHAS_SEM.FEC_FIN_SEMANA
       ELSE TRUNC(FECHAS_SEM.FEC_FIN_SEMANA, 'MM') - 1
    END As FEC_FIN_PROM_REAL,
    CASE
       WHEN TRUNC(FECHAS.FECHA_CONTABLE, 'MM') <= ADD_MONTHS(TRUNC(FECHAS_SEM.FEC_FIN_SEMANA, 'MM'), -1)
            OR (TRUNC(FECHAS.FECHA_CONTABLE, 'MM') = TRUNC(FECHAS_SEM.FEC_FIN_SEMANA, 'MM') AND FECHAS_SEM.FEC_FIN_SEMANA = LAST_DAY(FECHAS_SEM.FEC_FIN_SEMANA)) THEN
          1
       ELSE
          0
    END As PROMEDIAR_REAL
FROM
   (SELECT DISTINCT FECHAS.FEC_INI_ANIO_ACT + ROWNUM - 1 As FECHA_CONTABLE
   FROM FECHAS
   CONNECT By ROWNUM <= LAST_DAY(ADD_MONTHS(TRUNC(FECHAS.FEC_FIN_SEMANA, 'YYYY'), 11)) - FECHAS.FEC_INI_ANIO_ACT ) FECHAS,
   (
      ---------empieza REAL
   SELECT /*+ INDEX(GPV GPVINDXCONT) */ 
   GPV.fecha_contable,
   GPV.fecha_real,
   GPV.valor_numerico as GAS_ZT
   FROM GASRMN.gas_parametros_valores GPV, 
   FECHAS
   WHERE  GPV.id_parametros=1872
       AND GPV.plataforma=371
       AND GPV.fecha_contable BETWEEN FECHAS.FEC_INI_ANIO_ACT AND FECHAS.FEC_FIN_SEMANA) GAS_ZT_REAL,
       --------termina REAL
       
       --------empieza  Prog
   (SELECT TRUNC(PROG.DIA, 'MM') As FECHA_CONTABLE, 
   ROUND(AVG(PROG.POM), 4) AS GAS_ZT, ROUND(AVG(PROG.pot1), 4) AS GAS_POT
     FROM programas_gas_rmne PROG, FECHAS
     WHERE PROG.PRODUCTO='ZONA DE TRANSICION'
         AND PROG.DIA BETWEEN FECHAS.FEC_INI_ANIO_ACT AND LAST_DAY(ADD_MONTHS(TRUNC(FECHAS.FEC_FIN_SEMANA, 'YYYY'), 11))
      GROUP By TRUNC(PROG.DIA, 'MM')) GAS_ZT_PROG,
      FECHAS FECHAS_SEM
WHERE
   FECHAS.FECHA_CONTABLE = GAS_ZT_REAL.FECHA_CONTABLE(+)
   AND TRUNC(FECHAS.FECHA_CONTABLE, 'MM') = TRUNC(GAS_ZT_PROG.FECHA_CONTABLE(+), 'MM')






/* INDICE DE APROVECHAMIENTO DE GAS */


WITH FECHAS AS
(SELECT
  TO_DATE(:FECHA_INI_SEMANA, 'DD/MM/YYYY') - 1 As FEC_INI_SEMANA,
   TO_DATE(:FECHA_FIN_SEMANA, 'DD/MM/YYYY') - 1 As FEC_FIN_SEMANA,
   ADD_MONTHS(TRUNC(
          TO_DATE(:FECHA_FIN_SEMANA, 'DD/MM/YYYY') - 1
     , 'YYYY'),-12) As FEC_INI_ANIO_ANT,
    TRUNC(
         TO_DATE(:FECHA_FIN_SEMANA, 'DD/MM/YYYY') - 1
     , 'YYYY') As FEC_INI_ANIO_ACT
FROM DUAL)

SELECT
    FECHAS.FECHA_CONTABLE, FECHAS.FECHA_CONTABLE + 1 As FECHA_REAL,
    GAS_IAG_REAL.GAS_IAG As GAS_IAG_REAL, GAS_IAG_PROG.GAS_IAG As GAS_IAG_PROG,
    GAS_IAG_POT.GAS_IAG As GAS_IAG_POT1,
    FECHAS_SEM.FEC_INI_SEMANA, FECHAS_SEM.FEC_FIN_SEMANA, FECHAS_SEM.FEC_INI_ANIO_ANT,
    FECHAS_SEM.FEC_INI_ANIO_ACT,
    CASE
       WHEN FECHAS_SEM.FEC_FIN_SEMANA = LAST_DAY(FECHAS_SEM.FEC_FIN_SEMANA) THEN FECHAS_SEM.FEC_FIN_SEMANA
       ELSE TRUNC(FECHAS_SEM.FEC_FIN_SEMANA, 'MM') - 1
    END As FEC_FIN_PROM_REAL,
    CASE
       WHEN TRUNC(FECHAS.FECHA_CONTABLE, 'MM') <= ADD_MONTHS(TRUNC(FECHAS_SEM.FEC_FIN_SEMANA, 'MM'), -1)
            OR (TRUNC(FECHAS.FECHA_CONTABLE, 'MM') = TRUNC(FECHAS_SEM.FEC_FIN_SEMANA, 'MM') AND FECHAS_SEM.FEC_FIN_SEMANA = LAST_DAY(FECHAS_SEM.FEC_FIN_SEMANA)) THEN
          1
       ELSE
          0
    END As PROMEDIAR_REAL
FROM
   (SELECT DISTINCT FECHAS.FEC_INI_ANIO_ACT + ROWNUM - 1 As FECHA_CONTABLE
   FROM FECHAS
   CONNECT By ROWNUM <= LAST_DAY(ADD_MONTHS(TRUNC(FECHAS.FEC_FIN_SEMANA, 'YYYY'), 11)) - FECHAS.FEC_INI_ANIO_ACT ) FECHAS,
   (SELECT GPV.FECHA AS fecha_contable,GPV.FECHA+1 AS fecha_real,(GPV.IAG*100) as GAS_IAG
   FROM gas_grafica GPV, FECHAS
   WHERE 
              (('RMNE' in (:ACTIVO) and GPV.activo = 'RMNE') or ('RMNE' not in (:ACTIVO) and GPV.activo <> 'RMNE' AND GPV.activo in(:ACTIVO)))
       AND GPV.fecha BETWEEN FECHAS.FEC_INI_ANIO_ACT AND FECHAS.FEC_FIN_SEMANA) GAS_IAG_REAL,
   (SELECT TRUNC(PROG.FECHA, 'MM') As FECHA_CONTABLE, ROUND(AVG(PROG.IAGC*100), 4) AS GAS_IAG
     FROM gas_grafica PROG, FECHAS
     WHERE 
                (('RMNE' in (:ACTIVO) and PROG.activo = 'RMNE') or ('RMNE' not in (:ACTIVO) and PROG.activo <> 'RMNE' AND PROG.activo in(:ACTIVO)))
         AND PROG.fecha BETWEEN FECHAS.FEC_INI_ANIO_ACT AND LAST_DAY(ADD_MONTHS(TRUNC(FECHAS.FEC_FIN_SEMANA, 'YYYY'), 11))
      GROUP By TRUNC(PROG.FECHA, 'MM')) GAS_IAG_PROG,
      (SELECT TRUNC(POT.FECHA_CONTABLE, 'MM') As FECHA_CONTABLE, ROUND(AVG(POT.IAG_POT1), 4) AS GAS_IAG
     FROM DATAWAREZM.POS_GH_N2_PROY_VARS POT, FECHAS
     WHERE 
                ('RMNE' in (:ACTIVO) And POT.TIPO = 'R' And POT.valor_tipo = 'RMNE')
        AND POT.fecha_contable BETWEEN FECHAS.FEC_INI_ANIO_ACT AND LAST_DAY(ADD_MONTHS(TRUNC(FECHAS.FEC_FIN_SEMANA, 'YYYY'), 11))
      GROUP By TRUNC(POT.FECHA_CONTABLE, 'MM')) GAS_IAG_POT,
      FECHAS FECHAS_SEM
WHERE
   FECHAS.FECHA_CONTABLE = GAS_IAG_REAL.FECHA_CONTABLE(+)
   AND TRUNC(FECHAS.FECHA_CONTABLE, 'MM') = TRUNC(GAS_IAG_PROG.FECHA_CONTABLE(+), 'MM')
   AND TRUNC(FECHAS.FECHA_CONTABLE, 'MM') = TRUNC(GAS_IAG_POT.FECHA_CONTABLE(+), 'MM')







/*BUENO*/



SELECT GAS_IAG.FECHA_CONTABLE,GAS_IAG.ACTIVO,GAS_IAG.GAS_IAG,ZT.GAS_ZT FROM


 (SELECT GPV.FECHA AS fecha_contable,(GPV.IAG*100) as GAS_IAG, ACTIVO
   FROM gas_grafica GPV where fecha = :FECHA+1 and activo in ('CANTARELL','KU MALOOB ZAAP')) GAS_IAG,
  
   (SELECT 
   GPV.fecha_contable,
   GPV.valor_numerico as GAS_ZT,plata.activo as activo
   FROM GASRMN.gas_parametros_valores GPV,GASRMN.gas_plataformas plata
   WHERE  GPV.id_parametros=1872
       AND GPV.plataforma=371 and
       GPV.plataforma=plata.id_plataformas
      and fecha_contable = :FECHA+1 
     )ZT
     
    
WHERE GAS_IAG.ACTIVO=ZT.ACTIVO(+) 

UNION ALL 


SELECT TO_DATE(:FECHA,'dd/MM/yyyy')+1 AS FECHA, 'REGIONAL' AS ACTIVO, GAS_IAG.GAS_IAG,SUM(REGIONAL.GAS_ZT) AS ZT_REGIONAL
FROM
(SELECT GPV.FECHA AS fecha_contable,(GPV.IAG*100) as GAS_IAG, ACTIVO
   FROM gas_grafica GPV where fecha = :FECHA+1 and activo='RMNE') GAS_IAG,


(SELECT 
   GPV.fecha_contable,
   GPV.valor_numerico as GAS_ZT,plata.activo as activo
   FROM GASRMN.gas_parametros_valores GPV,GASRMN.gas_plataformas plata
   WHERE  GPV.id_parametros=1872
       AND GPV.plataforma=371 and
       GPV.plataforma=plata.id_plataformas
      and fecha_contable = :FECHA+1 )REGIONAL


GROUP BY TO_DATE(:FECHA,'dd/MM/yyyy'),'REGIONAL',GAS_IAG.GAS_IAG


UNION ALL


SELECT TO_DATE(:FECHA,'dd/MM/yyyy')+1 AS FECHA, 'PROM_MES' AS ACTIVO,IAG_PROM.GAS_IAG,ZT_PROM.GAS_ZT
FROM


(SELECT ROUND(AVG(GPV.IAG*100),2) as GAS_IAG
   FROM gas_grafica GPV WHERE FECHA BETWEEN TRUNC(:FECHA,'MM') AND :FECHA+1)IAG_PROM,
    
      
  (SELECT 
  
   ROUND(AVG(GPV.valor_numerico),2) as GAS_ZT
   FROM GASRMN.gas_parametros_valores GPV,GASRMN.gas_plataformas plata
   WHERE  GPV.id_parametros=1872
       AND GPV.plataforma=371 and
       GPV.plataforma=plata.id_plataformas
      and fecha_contable BETWEEN TRUNC(:FECHA,'MM') AND :FECHA+1)ZT_PROM