
Insert into XSIEDE.RMN_SIE_TOTALES
   (NO_SAP, REGION, ACTIVO, C_PROCESO, PLATAFORMA, EQUIPO, AGRUPADOR, FECHA_CONTABLE, FECHA_REAL, MES, ANIO, TIPO_INSTALACION, ID_EQUIPO, REPORTE)
SELECT EQ.NO_SAP, EQ.REGION, EQ.ACTIVO, EQ.C_PROCESO, EQ.PLATAFORMA, EQ.EQUIPO, EQ.AGRUPADOR, FECHA.FECHA_CONTABLE, FECHA.FECHA_REAL, EQ.MES, EQ.ANIO, EQ.TIPO_INSTALACION, EQ.ID_EQUIPO, EQ.REPORTE FROM 
(SELECT * FROM RMN_SIE_TOTALES
WHERE ID_EQUIPO = 75117188 AND FECHA_CONTABLE = TO_DATE('16/06/2016','DD/MM/YYYY')) EQ,
(SELECT FECHA FECHA_CONTABLE, FECHA+1 AS FECHA_REAL
FROM (
SELECT LEVEL,TO_DATE('17/06/2016','DD/MM/YYYY')+LEVEL-1 FECHA
FROM DUAL
CONNECT BY LEVEL BETWEEN 1 AND TO_NUMBER(TO_DATE('30/06/2016','DD/MM/YYYY') - TO_DATE('17/06/2016','DD/MM/YYYY'))+1 )
ORDER BY FECHA DESC)FECHA














