
SELECT     ACTIVIDADES.ID_ACTIVIDADES, ACTIVIDADES.DESC_ACTIVIDADES,ACTIVIDADES.ID_GENERICO, AREA.ID_AREA, AREA.DESC_AREA, INSTALACION.ID_INSTALACION, 
                      INSTALACION.DESC_INSTALACION, ACTIVOS.ID_ACTIVO, ACTIVOS.DESC_ACTIVO,
EMPLEADO.NOMBRE + '  ' + EMPLEADO.APE_PAT + ' ' + EMPLEADO.APE_MAT  AS Evaluador, 
                      V_EMPLEADOS.nombre AS Empleado, ACTIVIDADES.CODIGO, EMPLEADO.FICHA, V_EMPLEADOS.FICHA AS ficha_emp,
actividades.tipo tipo, '' as supervisor
FROM         CATEGORIA_PROCEDIMIENTO INNER JOIN
                      ACTIVIDADES ON CATEGORIA_PROCEDIMIENTO.ID_ACTIVIDADES = ACTIVIDADES.ID_ACTIVIDADES INNER JOIN
                      AREA ON ACTIVIDADES.ID_AREA = AREA.ID_AREA INNER JOIN
                      INSTALACION ON AREA.ID_INSTALACION = INSTALACION.ID_INSTALACION INNER JOIN
                      ACTIVOS ON INSTALACION.ID_ACTIVO = ACTIVOS.ID_ACTIVO INNER JOIN
                      EMPLEADO ON AREA.ID_AREA = EMPLEADO.ID_AREA INNER JOIN
                      CATEGORIA_EMPLEADOS ON CATEGORIA_PROCEDIMIENTO.ID_CATEGORIA = CATEGORIA_EMPLEADOS.ID_CATEGORIA INNER JOIN
                      V_EMPLEADOS ON CATEGORIA_EMPLEADOS.FICHA = V_EMPLEADOS.FICHA
WHERE     (ACTIVIDADES.ID_ACTIVIDADES = 7602)  AND (EMPLEADO.FICHA = 17220)  AND (V_EMPLEADOS.FICHA =cast('00451165' as varchar(8)))
UNION
SELECT     ACTIVIDADES.ID_ACTIVIDADES, ACTIVIDADES.DESC_ACTIVIDADES,ACTIVIDADES.ID_GENERICO, AREA.ID_AREA, AREA.DESC_AREA, INSTALACION.ID_INSTALACION, 
                      INSTALACION.DESC_INSTALACION, ACTIVOS.ID_ACTIVO, ACTIVOS.DESC_ACTIVO,
EMPLEADO.NOMBRE + '  ' + EMPLEADO.APE_PAT + ' ' + EMPLEADO.APE_MAT  AS Evaluador, 
                      V_EMPLEADOS.nombre AS Empleado, ACTIVIDADES.CODIGO, EMPLEADO.FICHA, V_EMPLEADOS.FICHA AS ficha_emp,
actividades.tipo tipo, EMPLEADO.nombre as supervisor


FROM         procCritico_empleado INNER JOIN
                      ACTIVIDADES ON procCritico_empleado.ID_ACTIVIDADES = ACTIVIDADES.ID_ACTIVIDADES INNER JOIN
                      AREA ON ACTIVIDADES.ID_AREA = AREA.ID_AREA INNER JOIN
                      INSTALACION ON AREA.ID_INSTALACION = INSTALACION.ID_INSTALACION INNER JOIN
                      ACTIVOS ON INSTALACION.ID_ACTIVO = ACTIVOS.ID_ACTIVO INNER JOIN
                     -- EMPLEADO ON AREA.ID_AREA = EMPLEADO.ID_AREA INNER JOIN 
                      V_EMPLEADOS ON procCritico_empleado.FICHA_trabajador = V_EMPLEADOS.FICHA INNER JOIN
					EMPLEADO ON procCritico_empleado.Ficha_alta = EMPLEADO.Ficha						


WHERE     (ACTIVIDADES.ID_ACTIVIDADES = 7602) AND (V_EMPLEADOS.FICHA =cast('00451165' as varchar(8))) 









--MI CONSULTA
SELECT * from empleado,procCritico_empleado WHERE (procCritico_empleado.Ficha_alta= '17220') and (empleado.ficha='17220') 














--CNSULTAS DE APOYO


SELECT * FROM ProcCritico_Empleado where Ficha_alta = 17220


select * from empleado where ficha='17220'
select * from usuarios where ficha=17220

select * from V_EMPLEADOS where ficha=451165


SELECT * FROM ACTIVIDADES WHERE Ficha_alta.ProcCritico_Empleado=17220