select * from MNE_ACE_PROD_INTEG_CA

SELECT * FROM gas_plataformas WHERE ACTIVO='EK BALAM'

SELECT * FROM gas_parametros_valores

SELECT * FROM gas_c_horas WHERE ID_HORA LIKE '24'

SELECT * FROM MNE_ACE_VALOR_NUM






select * from MNE_ACE_CONTROL_AJUSTES_V




                 
           /*PRODUCCION INTERGADA ACTIVO CANTARELL*/
           
           
           SELECT FECHA_REAL, FECHA_CONTABLE,
  MAX(DECODE(PLATAFORMA, 'AKAL-AG1', PROD_INTEGRADA, NULL))AS "AKAL-AG1",
   MAX(DECODE(PLATAFORMA, 'AKAL-B1', PROD_INTEGRADA, NULL))AS "AKAL-B1",
   MAX(DECODE(PLATAFORMA, 'AKAL-C1', PROD_INTEGRADA, NULL))AS "AKAL-C1",
    MAX(DECODE(PLATAFORMA, 'AKAL-C2', PROD_INTEGRADA, NULL))AS "AKAL-C2",
    MAX(DECODE(PLATAFORMA, 'AKAL-C3', PROD_INTEGRADA, NULL))AS "AKAL-C3",
    MAX(DECODE(PLATAFORMA, 'AKAL-CPERF', PROD_INTEGRADA, NULL))AS "AKAL-CPERF",
    MAX(DECODE(PLATAFORMA, 'AKAL-J1', PROD_INTEGRADA, NULL))AS "AKAL-J1",
    MAX(DECODE(PLATAFORMA, 'AKAL-J2', PROD_INTEGRADA, NULL))AS "AKAL-J2", 
    MAX(DECODE(PLATAFORMA, 'AKAL-J3', PROD_INTEGRADA, NULL))AS "AKAL-J3", 
    MAX(DECODE(PLATAFORMA, 'AKAL-L', PROD_INTEGRADA, NULL))AS "AKAL-L",  
    MAX(DECODE(PLATAFORMA, 'AKAL-N', PROD_INTEGRADA, NULL))AS "AKAL-N", 
    MAX(DECODE(PLATAFORMA, 'AKAL-A1', PROD_INTEGRADA, NULL))AS "AKAL-A1",
    MAX(DECODE(PLATAFORMA, 'AKAL-A2', PROD_INTEGRADA, NULL))AS "AKAL-A2"    
  
  FROM               
                 
(SELECT
 GP.PLATAFORMA   
 ,TO_DATE(FECHAS.FECHA_REAL, 'DD/MM/YYYY') As FECHA_REAL
  ,TO_CHAR(TO_DATE(:FECHAINI, 'DD/MM/YYYY') + ROWNUM - 1, 'DD/MM/YYYY') As FECHA_CONTABLE
 ,TO_NUMBER(GAS_PARAMETROVALOR(778, FECHAS.FECHA_REAL, FECHAS.ID_HORA_05, GP.ID), '999999999999.99999') As PROD_INTEGRADA
 FROM GAS_PLATAFORMAS GP, MNE_ACE_CONTROL_AJUSTES_V AJUSTES_PLAT,
     (
       SELECT
            TO_CHAR(TO_DATE(:FECHAINI, 'DD/MM/YYYY') + ROWNUM, 'DD/MM/YYYY') As FECHA_REAL
           ,TO_CHAR(TO_DATE(:FECHAINI, 'DD/MM/YYYY') + ROWNUM - 1, 'DD/MM/YYYY') As FECHA_CONTABLE
           ,MNE_ACE_ID_HORA(TO_CHAR(TO_DATE(:FECHAINI, 'DD/MM/YYYY') + ROWNUM, 'DD/MM/YYYY'), '05:00') As ID_HORA_05
        FROM DUAL
        CONNECT By ROWNUM <= TO_NUMBER(TO_DATE(:FECHAFIN,'DD/MM/YYYY')-TO_DATE(:FECHAINI,'DD/MM/YYYY'))
     ) FECHAS
WHERE 
  GP.TIPO_INST = 'INSTANTANEA'
  AND GP.ACTIVO = 'CANTARELL'
  AND AJUSTES_PLAT.PLATAFORMA = GP.PLATAFORMA
  AND TO_DATE(FECHAS.FECHA_REAL, 'DD/MM/YYYY') BETWEEN AJUSTES_PLAT.FEC_VIGENCIA_INI AND FEC_VIGENCIA_FIN)
 GROUP BY FECHA_REAL
      
                 
          
                 
                 
                 
                 
   /*PRODUCCION INTEGRADA ACTIVO KMZ*/              
                 
                 
  SELECT FECHA_REAL-1 AS FECHA_REAL, FECHA_CONTABLE,
  MAX(DECODE(PLATAFORMA, 'EKUA1', PROD_INTEGRADA, NULL))AS EKUA1,
   MAX(DECODE(PLATAFORMA, 'FPSO', PROD_INTEGRADA, NULL))AS FPSO,
   MAX(DECODE(PLATAFORMA, 'PBKUH', PROD_INTEGRADA, NULL))AS PBKUH,
    MAX(DECODE(PLATAFORMA, 'PBKUM', PROD_INTEGRADA, NULL))AS PBKUM,
    MAX(DECODE(PLATAFORMA, 'PBKUS', PROD_INTEGRADA, NULL))AS PBKUS,
    MAX(DECODE(PLATAFORMA, 'PPKUA', PROD_INTEGRADA, NULL))AS PPKUA,
    MAX(DECODE(PLATAFORMA, 'ZAAP-C', PROD_INTEGRADA, NULL))AS "ZAAP-C"   
  
  FROM               
                 
(SELECT
 GP.PLATAFORMA   
 ,TO_DATE(FECHAS.FECHA_REAL, 'DD/MM/YYYY') As FECHA_REAL
  ,TO_CHAR(TO_DATE(:FECHAINI, 'DD/MM/YYYY') + ROWNUM - 1, 'DD/MM/YYYY') As FECHA_CONTABLE
 ,TO_NUMBER(GAS_PARAMETROVALOR(778, FECHAS.FECHA_REAL, FECHAS.ID_HORA_05, GP.ID), '999999999999.99999') As PROD_INTEGRADA
 FROM GAS_PLATAFORMAS GP, MNE_ACE_CONTROL_AJUSTES_V AJUSTES_PLAT,
     (
       SELECT
            TO_CHAR(TO_DATE(:FECHAINI, 'DD/MM/YYYY') + ROWNUM, 'DD/MM/YYYY') As FECHA_REAL
           ,TO_CHAR(TO_DATE(:FECHAINI, 'DD/MM/YYYY') + ROWNUM - 1, 'DD/MM/YYYY') As FECHA_CONTABLE
           ,MNE_ACE_ID_HORA(TO_CHAR(TO_DATE(:FECHAINI, 'DD/MM/YYYY') + ROWNUM, 'DD/MM/YYYY'), '05:00') As ID_HORA_05
        FROM DUAL
        CONNECT By ROWNUM <= TO_NUMBER(TO_DATE(:FECHAFIN,'DD/MM/YYYY')-TO_DATE(:FECHAINI,'DD/MM/YYYY'))
     ) FECHAS
WHERE 
  GP.TIPO_INST = 'INSTANTANEA'
  AND GP.ACTIVO = 'KU MALOOB ZAAP'
  AND AJUSTES_PLAT.PLATAFORMA = GP.PLATAFORMA
  AND TO_DATE(FECHAS.FECHA_REAL, 'DD/MM/YYYY') BETWEEN AJUSTES_PLAT.FEC_VIGENCIA_INI AND FEC_VIGENCIA_FIN)
 GROUP BY FECHA_REAL





/*SACA LAS BATERIAS POR ACTIVO*/

SELECT DISTINCT
 GP.ACTIVO,GP.PLATAFORMA   
  FROM GAS_PLATAFORMAS GP, MNE_ACE_CONTROL_AJUSTES_V AJUSTES_PLAT,
     (
       SELECT
            TO_CHAR(TO_DATE(:FECHAINI, 'DD/MM/YYYY') + ROWNUM, 'DD/MM/YYYY') As FECHA_REAL
           ,TO_CHAR(TO_DATE(:FECHAINI, 'DD/MM/YYYY') + ROWNUM - 1, 'DD/MM/YYYY') As FECHA_CONTABLE
           ,MNE_ACE_ID_HORA(TO_CHAR(TO_DATE(:FECHAINI, 'DD/MM/YYYY') + ROWNUM, 'DD/MM/YYYY'), '05:00') As ID_HORA_05
        FROM DUAL
        CONNECT By ROWNUM <= TO_NUMBER(TO_DATE(:FECHAFIN,'DD/MM/YYYY')-TO_DATE(:FECHAINI,'DD/MM/YYYY'))
     ) FECHAS
WHERE 
  GP.TIPO_INST = 'INSTANTANEA'
  AND GP.ACTIVO = 'CANTARELL'
  AND AJUSTES_PLAT.PLATAFORMA = GP.PLATAFORMA
  AND TO_DATE(FECHAS.FECHA_REAL, 'DD/MM/YYYY') BETWEEN AJUSTES_PLAT.FEC_VIGENCIA_INI AND FEC_VIGENCIA_FIN
  UNION
  
  SELECT GP.ACTIVO,'TODAS' AS TODAS
  FROM GAS_PLATAFORMAS GP
  WHERE ACTIVO='CANTARELL'





  SELECT FECHA_CONTABLE,FECHA_REAL, PROD_INTEGRADA
   
  FROM               
                 
(SELECT
 GP.PLATAFORMA   
,TO_DATE(FECHAS.FECHA_REAL, 'DD/MM/YYYY') As FECHA_REAL
 ,TO_DATE(FECHAS.FECHA_CONTABLE, 'DD/MM/YYYY') As FECHA_CONTABLE
 ,TO_NUMBER(GAS_PARAMETROVALOR(778, FECHAS.FECHA_REAL, FECHAS.ID_HORA_05, GP.ID), '999999999999.99999') As PROD_INTEGRADA
 FROM GAS_PLATAFORMAS GP, MNE_ACE_CONTROL_AJUSTES_V AJUSTES_PLAT,
     (
       SELECT
            TO_CHAR(TO_DATE(:FECHAINI, 'DD/MM/YYYY') + ROWNUM, 'DD/MM/YYYY') As FECHA_REAL
           ,TO_CHAR(TO_DATE(:FECHAINI, 'DD/MM/YYYY') + ROWNUM - 1, 'DD/MM/YYYY') As FECHA_CONTABLE
           ,MNE_ACE_ID_HORA(TO_CHAR(TO_DATE(:FECHAINI, 'DD/MM/YYYY') + ROWNUM, 'DD/MM/YYYY'), '05:00') As ID_HORA_05
        FROM DUAL
        CONNECT By ROWNUM <= TO_NUMBER(TO_DATE(:FECHAFIN,'DD/MM/YYYY')-TO_DATE(:FECHAINI,'DD/MM/YYYY'))
     ) FECHAS
WHERE 
  GP.TIPO_INST = 'INSTANTANEA'
  AND GP.ACTIVO = 'CANTARELL'
  AND GP.PLATAFORMA = 'NOHOCH-A1'
  AND AJUSTES_PLAT.PLATAFORMA = GP.PLATAFORMA
  AND TO_DATE(FECHAS.FECHA_REAL, 'DD/MM/YYYY') BETWEEN AJUSTES_PLAT.FEC_VIGENCIA_INI AND FEC_VIGENCIA_FIN)
 
      


select * from MNE_ACE_CONTROL_AJUSTES_V 


/*rollback*/

SELECT 
 GP.PLATAFORMA   
   ,TO_DATE(FECHAS.FECHA_REAL, 'DD/MM/YYYY') As FECHA_REAL
   ,TO_DATE(FECHAS.FECHA_CONTABLE, 'DD/MM/YYYY') As FECHA_CONTABLE
   ,TO_NUMBER(GAS_PARAMETROVALOR(778, FECHAS.FECHA_REAL, FECHAS.ID_HORA_05, GP.ID), '999999999999.99999') As PROD_INTEGRADA
 FROM GAS_PLATAFORMAS GP, MNE_ACE_CONTROL_AJUSTES_V AJUSTES_PLAT,
     (
        SELECT
            TO_CHAR(TO_DATE(:MES, 'MM/YYYY') + ROWNUM, 'DD/MM/YYYY') As FECHA_REAL
           ,TO_CHAR(TO_DATE(:MES, 'MM/YYYY') + ROWNUM - 1, 'DD/MM/YYYY') As FECHA_CONTABLE
           ,MNE_ACE_ID_HORA(TO_CHAR(TO_DATE(:MES, 'MM/YYYY') + ROWNUM, 'DD/MM/YYYY'), '05:00') As ID_HORA_05
        FROM DUAL
        CONNECT By ROWNUM <= TO_NUMBER(TO_CHAR(LAST_DAY(TO_DATE(:MES, 'MM/YYYY')), 'DD'), '99')
     ) FECHAS
WHERE 
  GP.TIPO_INST = 'INSTANTANEA'
  AND GP.ACTIVO = 'CANTARELL'
  AND AJUSTES_PLAT.PLATAFORMA = GP.PLATAFORMA
  AND TO_DATE(FECHAS.FECHA_REAL, 'DD/MM/YYYY') BETWEEN AJUSTES_PLAT.FEC_VIGENCIA_INI AND FEC_VIGENCIA_FIN
