INSERT INTO PROGRAMAS_GAS_RMNE (ACTIVO,PROYECTO,PRODUCTO,ANO,DIA)
SELECT ACTIVO,PROYECTO,PRODUCTO,TO_CHAR(SYSDATE,'yyyy') AS ANO, ADD_MONTHS(TRUNC(SYSDATE,'Month'),1) AS DIA FROM PROGRAMAS_GAS_RMNE WHERE DIA = TRUNC(SYSDATE,'Month'); 
COMMIT;
