




SELECT * FROM PRON_PROD WHERE DIA='18/DEC/2010'

SELECT * FROM PRON_MOVS WHERE CVE_TIPO='P'

SELECT * FROM PRON_JUST WHERE PROYECTO='CANTARELL' AND VOLUMEN='1.8'

SELECT * FROM ACEITENE.MNE_ACE_C_CONCEPTOS

SELECT * FROM PRON_PROD WHERE DIA='18/DEC/2010'



SELECT * FROM ACEITENE.MNE_ACE_JUST_POS WHERE PROYECTO='CANTARELL' AND FECHA_CONTABLE='18/DEC/2010' 


SELECT * FROM PRON_JUST WHERE PROYECTO='CANTARELL' AND FECHA_CONTABLE='18/DEC/2010'

/*CONSULTAS BUENAS*/


SELECT DISTINCT PRON_PROD.PROD_REAL, MNE_ACE_JUST_POS.VOLUMEN
FROM PRON_PROD INNER JOIN
ACEITENE.MNE_ACE_JUST_POS ON MNE_ACE_JUST_POS.FECHA_CONTABLE=PRON_PROD.DIA 

WHERE MNE_ACE_JUST_POS.FECHA_CONTABLE='18/DEC/2010' AND PRON_PROD.PROYECTO='CANTARELL'



SELECT PRON_PROD.PROD_REAL, MNE_ACE_JUST_POS.VOLUMEN
FROM PRON_PROD, ACEITENE.MNE_ACE_JUST_POS
WHERE PRON_PROD.DIA=MNE_ACE_JUST_POS.FECHA_CONTABLE AND (MNE_ACE_JUST_POS.FECHA_CONTABLE='18/DEC/2010' AND PRON_PROD.PROYECTO='CANTARELL')