SELECT * FROM PRON_JUST WHERE FECHA_CONTABLE='08/FEB/2011' AND PROYECTO IN ('CANTARELL','EK BALAM')

SELECT * FROM PRON_PROD

SELECT * FROM PRON_ACTIV

SELECT * FROM PROGRAMAS_GAS_RMNE


/*VOLUMEN POR SEMANA*/
SELECT * FROM(


SELECT PROYECTO, DET_CONCEPTO, SUM(VOLUMEN), ABS(SUM(VOLUMEN))

FROM PRON_JUST 

WHERE 
    FECHA_CONTABLE IN (SELECT
    TO_DATE(TO_CHAR(TO_DATE('08/FEB/2011','DD/MM/YYYY') + (1-TO_CHAR(TO_DATE('08/FEB/2011','DD/MM/YYYY'),'D')), 'DD/MM/YYYY'),'DD/MM/YYYY')-1 + ROWNUM
    FROM DUAL
    CONNECT BY ROWNUM <= 7) 
AND PROYECTO IN ('CANTARELL','EK BALAM','KU MALOOB ZAAP','GTDH','RMNE')
GROUP BY PROYECTO, DET_CONCEPTO

ORDER BY ABS(SUM(VOLUMEN)) DESC 
)

WHERE ROWNUM <=8


















/*VOLUME POR DIA*/



SELECT * FROM(

SELECT PROYECTO, DET_CONCEPTO, SUM(VOLUMEN) AS "VOLUMEN DIARIO", ABS(SUM(VOLUMEN))

FROM PRON_JUST 

WHERE
    FECHA_CONTABLE+1=TO_DATE('08/FEB/2011','DD/MM/YYYY')
    AND PROYECTO IN ('CANTARELL','EK BALAM','KU MALOOB ZAAP','GTDH','RMNE')
      
 GROUP BY PROYECTO, DET_CONCEPTO
    ORDER BY ABS(SUM(VOLUMEN)) DESC, SUM(VOLUMEN) DESC)
    
    WHERE ROWNUM<=6



SELECT * FROM(SELECT SUM(VOLUMEN) AS "VOLUMEN DIARIO" FROM PRON_JUST WHERE FECHA_CONTABLE+1=TO_DATE('08/FEB/2011','DD/MM/YYYY') AND PROYECTO IN ('KU MALOOB ZAAP') GROUP BY PROYECTO ORDER BY ABS(SUM(VOLUMEN)) DESC, SUM(VOLUMEN) DESC) WHERE ROWNUM<=6


