/* FECHA DE INICIO Y FIN DE SEMANA DE LA FECHA ACTUAL
    - CONSULTA DESARROLLADA PARA MANEJAR MAS RAPIDO LOS SUBQUERYES -
 */
WITH FECHAS AS
(SELECT
   TO_DATE(:FECHA_INI_SEMANA, 'DD/MM/YYYY') - 1 As FEC_INI_SEMANA,
   TO_DATE(:FECHA_FIN_SEMANA, 'DD/MM/YYYY') - 1 As FEC_FIN_SEMANA
FROM DUAL)   


SELECT
   FECHAS.FEC_INI_SEMANA,
   FECHAS.FEC_FIN_SEMANA,
   /* PROYECTADO */
   NVL(INCREMENTOS_PROY.CA_VOL_TERMINACIONES_PROY, 0) As CA_VOL_TERMINACIONES_PROY,
   NVL(INCREMENTOS_PROY.CA_VOL_REP_MENORES_PROY, 0) As CA_VOL_REP_MENORES_PROY,
   NVL(INCREMENTOS_PROY.CA_VOL_REP_MAYORES_PROY, 0) As CA_VOL_REP_MAYORES_PROY,
   NVL(INCREMENTOS_PROY.CA_VOL_ESTIMULACIONES_PROY, 0) As CA_VOL_ESTIMULACIONES_PROY,
   NVL(INCREMENTOS_PROY.KU_VOL_TERMINACIONES_PROY, 0) As KU_VOL_TERMINACIONES_PROY,
   NVL(INCREMENTOS_PROY.KU_VOL_REP_MENORES_PROY, 0) As KU_VOL_REP_MENORES_PROY,
   NVL(INCREMENTOS_PROY.KU_VOL_REP_MAYORES_PROY, 0) As KU_VOL_REP_MAYORES_PROY,
   NVL(INCREMENTOS_PROY.KU_VOL_ESTIMULACIONES_PROY, 0) As KU_VOL_ESTIMULACIONES_PROY,
   
   NVL(INCREMENTOS_PROY.CA_NUM_TERMINACIONES_PROY, 0) As CA_NUM_TERMINACIONES_PROY,
   NVL(INCREMENTOS_PROY.CA_NUM_REP_MENORES_PROY, 0) As CA_NUM_REP_MENORES_PROY,
   NVL(INCREMENTOS_PROY.CA_NUM_REP_MAYORES_PROY, 0) As CA_NUM_REP_MAYORES_PROY,
   NVL(INCREMENTOS_PROY.CA_NUM_ESTIMULACIONES_PROY, 0) As CA_NUM_ESTIMULACIONES_PROY,
   NVL(INCREMENTOS_PROY.KU_NUM_TERMINACIONES_PROY, 0) As KU_NUM_TERMINACIONES_PROY,
   NVL(INCREMENTOS_PROY.KU_NUM_REP_MENORES_PROY, 0) As KU_NUM_REP_MENORES_PROY,
   NVL(INCREMENTOS_PROY.KU_NUM_REP_MAYORES_PROY, 0) As KU_NUM_REP_MAYORES_PROY,
   NVL(INCREMENTOS_PROY.KU_NUM_ESTIMULACIONES_PROY, 0) As KU_NUM_ESTIMULACIONES_PROY,
   /* REAL */
   NVL(INCREMENTOS_REAL.CA_VOL_TERMINACIONES_REAL, 0) As CA_VOL_TERMINACIONES_REAL,
   NVL(INCREMENTOS_REAL.CA_VOL_REP_MENORES_REAL, 0) As CA_VOL_REP_MENORES_REAL,
   NVL(INCREMENTOS_REAL.CA_VOL_REP_MAYORES_REAL, 0) As CA_VOL_REP_MAYORES_REAL,
   NVL(INCREMENTOS_REAL.CA_VOL_ESTIMULACIONES_REAL, 0) As CA_VOL_ESTIMULACIONES_REAL,
   NVL(INCREMENTOS_REAL.KU_VOL_TERMINACIONES_REAL, 0) As KU_VOL_TERMINACIONES_REAL,
   NVL(INCREMENTOS_REAL.KU_VOL_REP_MENORES_REAL, 0) As KU_VOL_REP_MENORES_REAL,
   NVL(INCREMENTOS_REAL.KU_VOL_REP_MAYORES_REAL, 0) As KU_VOL_REP_MAYORES_REAL,
   NVL(INCREMENTOS_REAL.KU_VOL_ESTIMULACIONES_REAL, 0) As KU_VOL_ESTIMULACIONES_REAL,
   
   NVL(INCREMENTOS_REAL.CA_NUM_TERMINACIONES_REAL, 0) As CA_NUM_TERMINACIONES_REAL,
   NVL(INCREMENTOS_REAL.CA_NUM_REP_MENORES_REAL, 0) As CA_NUM_REP_MENORES_REAL,
   NVL(INCREMENTOS_REAL.CA_NUM_REP_MAYORES_REAL, 0) As CA_NUM_REP_MAYORES_REAL,
   NVL(INCREMENTOS_REAL.CA_NUM_ESTIMULACIONES_REAL, 0) As CA_NUM_ESTIMULACIONES_REAL,
   NVL(INCREMENTOS_REAL.KU_NUM_TERMINACIONES_REAL, 0) As KU_NUM_TERMINACIONES_REAL,
   NVL(INCREMENTOS_REAL.KU_NUM_REP_MENORES_REAL, 0) As KU_NUM_REP_MENORES_REAL,
   NVL(INCREMENTOS_REAL.KU_NUM_REP_MAYORES_REAL, 0) As KU_NUM_REP_MAYORES_REAL,
   NVL(INCREMENTOS_REAL.KU_NUM_ESTIMULACIONES_REAL, 0) As KU_NUM_ESTIMULACIONES_REAL,
   CUENTA_POZOS.REALES_CA,CUENTA_POZOS.PROGRAMADOS_CA,CUENTA_POZOS.REALES_KU,CUENTA_POZOS.PROGRAMADOS_KU
FROM
    (SELECT
         /* CANTARELL */
         SUM(CASE WHEN PRON_JUST.PROYECTO IN( 'CANTARELL', 'EK BALAM') AND PRON_JUST.ID_DET_CONCEPTO = 59 THEN PRON_JUST.VOLUMEN ELSE NULL END) As CA_VOL_TERMINACIONES_REAL,
         SUM(CASE WHEN PRON_JUST.PROYECTO IN( 'CANTARELL', 'EK BALAM') AND PRON_JUST.ID_DET_CONCEPTO = 60 THEN PRON_JUST.VOLUMEN ELSE NULL END) As CA_VOL_REP_MENORES_REAL,
         SUM(CASE WHEN PRON_JUST.PROYECTO IN( 'CANTARELL', 'EK BALAM') AND PRON_JUST.ID_DET_CONCEPTO = 61 THEN PRON_JUST.VOLUMEN ELSE NULL END) As CA_VOL_REP_MAYORES_REAL,
         SUM(CASE WHEN PRON_JUST.PROYECTO IN( 'CANTARELL', 'EK BALAM') AND PRON_JUST.ID_DET_CONCEPTO = 62 THEN PRON_JUST.VOLUMEN ELSE NULL END) As CA_VOL_ESTIMULACIONES_REAL,
         
         COUNT(CASE WHEN PRON_JUST.PROYECTO IN( 'CANTARELL', 'EK BALAM') AND PRON_JUST.ID_DET_CONCEPTO = 59 THEN 1 ELSE NULL END) As CA_NUM_TERMINACIONES_REAL,
         COUNT(CASE WHEN PRON_JUST.PROYECTO IN( 'CANTARELL', 'EK BALAM') AND PRON_JUST.ID_DET_CONCEPTO = 60 THEN 1 ELSE NULL END) As CA_NUM_REP_MENORES_REAL,
         COUNT(CASE WHEN PRON_JUST.PROYECTO IN( 'CANTARELL', 'EK BALAM') AND PRON_JUST.ID_DET_CONCEPTO = 61 THEN 1 ELSE NULL END) As CA_NUM_REP_MAYORES_REAL,
         COUNT(CASE WHEN PRON_JUST.PROYECTO IN( 'CANTARELL', 'EK BALAM') AND PRON_JUST.ID_DET_CONCEPTO = 62 THEN 1 ELSE NULL END) As CA_NUM_ESTIMULACIONES_REAL,
         /* KU MALOOB ZAAP */
         SUM(CASE WHEN PRON_JUST.PROYECTO = 'KU MALOOB ZAAP' AND PRON_JUST.ID_DET_CONCEPTO = 59 THEN PRON_JUST.VOLUMEN ELSE NULL END) As KU_VOL_TERMINACIONES_REAL,
         SUM(CASE WHEN PRON_JUST.PROYECTO = 'KU MALOOB ZAAP' AND PRON_JUST.ID_DET_CONCEPTO = 60 THEN PRON_JUST.VOLUMEN ELSE NULL END) As KU_VOL_REP_MENORES_REAL,
         SUM(CASE WHEN PRON_JUST.PROYECTO = 'KU MALOOB ZAAP' AND PRON_JUST.ID_DET_CONCEPTO = 61 THEN PRON_JUST.VOLUMEN ELSE NULL END) As KU_VOL_REP_MAYORES_REAL,
         SUM(CASE WHEN PRON_JUST.PROYECTO = 'KU MALOOB ZAAP' AND PRON_JUST.ID_DET_CONCEPTO = 62 THEN PRON_JUST.VOLUMEN ELSE NULL END) As KU_VOL_ESTIMULACIONES_REAL,
         
         COUNT(CASE WHEN PRON_JUST.PROYECTO = 'KU MALOOB ZAAP' AND PRON_JUST.ID_DET_CONCEPTO = 59 THEN 1 ELSE NULL END) As KU_NUM_TERMINACIONES_REAL,
         COUNT(CASE WHEN PRON_JUST.PROYECTO = 'KU MALOOB ZAAP' AND PRON_JUST.ID_DET_CONCEPTO = 60 THEN 1 ELSE NULL END) As KU_NUM_REP_MENORES_REAL,
         COUNT(CASE WHEN PRON_JUST.PROYECTO = 'KU MALOOB ZAAP' AND PRON_JUST.ID_DET_CONCEPTO = 61 THEN 1 ELSE NULL END) As KU_NUM_REP_MAYORES_REAL,
         COUNT(CASE WHEN PRON_JUST.PROYECTO = 'KU MALOOB ZAAP' AND PRON_JUST.ID_DET_CONCEPTO = 62 THEN 1 ELSE NULL END) As KU_NUM_ESTIMULACIONES_REAL
     FROM PRON_JUST, FECHAS
     WHERE PRON_JUST.FECHA_CONTABLE BETWEEN FECHAS.FEC_INI_SEMANA AND FECHAS.FEC_FIN_SEMANA
         AND PRON_JUST.PROYECTO IN( 'CANTARELL', 'KU MALOOB ZAAP' )
         AND PRON_JUST.ID_DET_CONCEPTO BETWEEN 59 AND 62) INCREMENTOS_REAL,
    (     SELECT
         /* CANTARELL */
         SUM(CASE WHEN POS.PROYECTO IN( 'CANTARELL', 'EK BALAM') AND POS.ID_DET_CONCEPTO = 59 THEN POS.VOLUMEN ELSE NULL END) As CA_VOL_TERMINACIONES_PROY,
         SUM(CASE WHEN POS.PROYECTO IN( 'CANTARELL', 'EK BALAM') AND POS.ID_DET_CONCEPTO = 60 THEN POS.VOLUMEN ELSE NULL END) As CA_VOL_REP_MENORES_PROY,
         SUM(CASE WHEN POS.PROYECTO IN( 'CANTARELL', 'EK BALAM') AND POS.ID_DET_CONCEPTO = 61 THEN POS.VOLUMEN ELSE NULL END) As CA_VOL_REP_MAYORES_PROY,
         SUM(CASE WHEN POS.PROYECTO IN( 'CANTARELL', 'EK BALAM') AND POS.ID_DET_CONCEPTO = 62 THEN POS.VOLUMEN ELSE NULL END) As CA_VOL_ESTIMULACIONES_PROY,

         COUNT(CASE WHEN POS.PROYECTO IN( 'CANTARELL', 'EK BALAM') AND POS.ID_DET_CONCEPTO = 59 THEN 1 ELSE NULL END) As CA_NUM_TERMINACIONES_PROY,
         SUM(CASE WHEN POS.PROYECTO IN( 'CANTARELL', 'EK BALAM') AND POS.ID_DET_CONCEPTO = 60 THEN 1 ELSE NULL END) As CA_NUM_REP_MENORES_PROY,
         SUM(CASE WHEN POS.PROYECTO IN( 'CANTARELL', 'EK BALAM') AND POS.ID_DET_CONCEPTO = 61 THEN 1 ELSE NULL END) As CA_NUM_REP_MAYORES_PROY,
         SUM(CASE WHEN POS.PROYECTO IN( 'CANTARELL', 'EK BALAM') AND POS.ID_DET_CONCEPTO = 62 THEN 1 ELSE NULL END) As CA_NUM_ESTIMULACIONES_PROY,
         /* KU MALOOB ZAAP */
         SUM(CASE WHEN POS.PROYECTO = 'KU MALOOB ZAAP' AND POS.ID_DET_CONCEPTO = 59 THEN POS.VOLUMEN ELSE NULL END) As KU_VOL_TERMINACIONES_PROY,
         SUM(CASE WHEN POS.PROYECTO = 'KU MALOOB ZAAP' AND POS.ID_DET_CONCEPTO = 60 THEN POS.VOLUMEN ELSE NULL END) As KU_VOL_REP_MENORES_PROY,
         SUM(CASE WHEN POS.PROYECTO = 'KU MALOOB ZAAP' AND POS.ID_DET_CONCEPTO = 61 THEN POS.VOLUMEN ELSE NULL END) As KU_VOL_REP_MAYORES_PROY,
         SUM(CASE WHEN POS.PROYECTO = 'KU MALOOB ZAAP' AND POS.ID_DET_CONCEPTO = 62 THEN POS.VOLUMEN ELSE NULL END) As KU_VOL_ESTIMULACIONES_PROY,
         
         COUNT(CASE WHEN POS.PROYECTO = 'KU MALOOB ZAAP' AND POS.ID_DET_CONCEPTO = 59 THEN 1 ELSE NULL END) As KU_NUM_TERMINACIONES_PROY,
         COUNT(CASE WHEN POS.PROYECTO = 'KU MALOOB ZAAP' AND POS.ID_DET_CONCEPTO = 60 THEN 1 ELSE NULL END) As KU_NUM_REP_MENORES_PROY,
         COUNT(CASE WHEN POS.PROYECTO = 'KU MALOOB ZAAP' AND POS.ID_DET_CONCEPTO = 61 THEN 1 ELSE NULL END) As KU_NUM_REP_MAYORES_PROY,
         COUNT(CASE WHEN POS.PROYECTO = 'KU MALOOB ZAAP' AND POS.ID_DET_CONCEPTO = 62 THEN 1 ELSE NULL END) As KU_NUM_ESTIMULACIONES_PROY
     FROM datawarezm.MNE_ACE_JUST_POS POS, FECHAS
     WHERE POS.FECHA_CONTABLE BETWEEN FECHAS.FEC_INI_SEMANA AND FECHAS.FEC_FIN_SEMANA
         AND POS.PROYECTO IN( 'CANTARELL', 'EK BALAM', 'KU MALOOB ZAAP' )
         AND POS.ID_DET_CONCEPTO BETWEEN 59 AND 62) INCREMENTOS_PROY,
         
         (SELECT SUM(REALES_CA)AS REALES_CA,SUM(PROGRAMADOS_CA)AS PROGRAMADOS_CA,
 SUM(REALES_KU)AS REALES_KU,SUM(PROGRAMADOS_KU)AS PROGRAMADOS_KU      
         
         FROM
         
 ( SELECT  
  CASE
   WHEN TIPO='R' AND ACTIVO='CANTARELL' THEN POZOS
 ELSE NULL
 END AS REALES_CA,
 
 CASE
    WHEN TIPO='P' AND ACTIVO='CANTARELL' THEN POZOS
    ELSE NULL
    END AS PROGRAMADOS_CA,
     
     CASE
   WHEN TIPO='R' AND ACTIVO='KU MALOOB ZAAP' THEN POZOS
 ELSE NULL
 END AS REALES_KU,
 
 CASE
    WHEN TIPO='P' AND ACTIVO='KU MALOOB ZAAP' THEN POZOS
    ELSE NULL
    END AS PROGRAMADOS_KU
    
    FROM         

(SELECT
            activo,
            tipo,
            SUM(contador_pozos)AS POZOS
    FROM
      
        (SELECT
            DECODE(just.proyecto, 'EK BALAM', 'CANTARELL', just.proyecto) As activo,
           just.id_det_concepto, 
            COUNT(DISTINCT MOVS.ID_INSTALACION) As contador_pozos,
            'R' AS tipo
        FROM pron_just just, pron_movs movs
        WHERE just.id_justificacion = movs.id_justificacion
            AND just.fecha_contable + 1 BETWEEN 
                    TO_DATE(:FECHA_INI_SEMANA, 'DD/MM/YYYY') AND TO_DATE(:FECHA_FIN_SEMANA, 'DD/MM/YYYY')
            AND just.id_det_concepto IN (59,60,61,62)
            AND movs.cve_tipo = 'P'
            AND just.proyecto IN( 'CANTARELL', 'EK BALAM', 'KU MALOOB ZAAP' )
          AND NOT EXISTS(SELECT 'x' FROM pron_just just2, pron_movs movs2 WHERE just2.id_justificacion = movs2.id_justificacion And just2.fecha_contable between TO_DATE(:FECHA_INI_SEMANA, 'DD/MM/YYYY') - 15 And TO_DATE(:FECHA_INI_SEMANA, 'DD/MM/YYYY') - 2 And just2.id_det_concepto = just.id_det_concepto And just2.proyecto = just.proyecto And movs2.cve_tipo = 'P' And movs2.id_instalacion = movs.id_instalacion)      
         GROUP BY DECODE(just.proyecto, 'EK BALAM', 'CANTARELL', just.proyecto), just.id_det_concepto
            
        UNION ALL
        
        SELECT
            DECODE(just.proyecto, 'EK BALAM', 'CANTARELL', just.proyecto) As activo,
            just.id_det_concepto, 
            COUNT(DISTINCT MOVS.ID_INSTALACION) As contador_pozos,
            'P' AS tipo
        FROM datawarezm.mne_ace_just_pos just, datawarezm.mne_ace_movs_pos movs
        WHERE just.id_just_pos = movs.id_just_pos
        AND just.fecha_contable + 1 BETWEEN 
                    TO_DATE(:FECHA_INI_SEMANA, 'DD/MM/YYYY') AND TO_DATE(:FECHA_FIN_SEMANA, 'DD/MM/YYYY')
        AND just.id_det_concepto IN (59,60,61,62)
        AND movs.cve_tipo = 'P'
        AND just.proyecto IN( 'CANTARELL', 'EK BALAM', 'KU MALOOB ZAAP' )
        AND NOT EXISTS(SELECT 'x' FROM pron_just just2, pron_movs movs2 WHERE just2.id_justificacion = movs2.id_justificacion And just2.fecha_contable between TO_DATE(:FECHA_INI_SEMANA, 'DD/MM/YYYY') - 8 And TO_DATE(:FECHA_INI_SEMANA, 'DD/MM/YYYY') - 2 And just2.id_det_concepto = just.id_det_concepto And just2.proyecto = just.proyecto And movs2.cve_tipo = 'P' And movs2.id_instalacion = movs.id_instalacion)      
       AND NOT EXISTS (SELECT 'x' FROM datawarezm.mne_ace_just_pos just2, datawarezm.mne_ace_movs_pos movs2 WHERE just2.id_just_pos = movs2.id_just_pos And just2.fecha_contable between TO_DATE(:FECHA_INI_SEMANA, 'DD/MM/YYYY') - 1 And TO_DATE(:FECHA_FIN_SEMANA, 'DD/MM/YYYY') - 1 And just2.id_det_concepto = just.id_det_concepto And movs2.cve_tipo = 'P' And movs2.id_instalacion = movs.id_instalacion  And just2.realizado='R')
        GROUP BY DECODE(just.proyecto, 'EK BALAM', 'CANTARELL', just.proyecto), just.id_det_concepto)
        GROUP BY ACTIVO,TIPO
        
        ))) CUENTA_POZOS, FECHAS
         
         
         
         
         
         
         
         
         
     
         
         
         
         
 (SELECT SUM(REALES_CA)AS REALES_CA,SUM(PROGRAMADOS_CA)AS PROGARMADOS_CA,
 SUM(REALES_KU)AS REALES_KU,SUM(PROGRAMADOS_KU)AS PROGRAMADOS_KU      
         
         FROM
         
 ( SELECT  
  CASE
   WHEN TIPO='R' AND ACTIVO='CANTARELL' THEN POZOS
 ELSE NULL
 END AS REALES_CA,
 
 CASE
    WHEN TIPO='P' AND ACTIVO='CANTARELL' THEN POZOS
    ELSE NULL
    END AS PROGRAMADOS_CA,
     
     CASE
   WHEN TIPO='R' AND ACTIVO='KU MALOOB ZAAP' THEN POZOS
 ELSE NULL
 END AS REALES_KU,
 
 CASE
    WHEN TIPO='P' AND ACTIVO='KU MALOOB ZAAP' THEN POZOS
    ELSE NULL
    END AS PROGRAMADOS_KU
    
    FROM         

(SELECT
            activo,
            tipo,
            SUM(contador_pozos)AS POZOS
    FROM
      
        (SELECT
            DECODE(just.proyecto, 'EK BALAM', 'CANTARELL', just.proyecto) As activo,
           just.id_det_concepto, 
            COUNT(DISTINCT MOVS.ID_INSTALACION) As contador_pozos,
            'R' AS tipo
        FROM pron_just just, pron_movs movs
        WHERE just.id_justificacion = movs.id_justificacion
            AND just.fecha_contable + 1 BETWEEN 
                    TO_DATE(:FECHA_INI, 'DD/MM/YYYY') AND TO_DATE(:FECHA_FIN, 'DD/MM/YYYY')
            AND just.id_det_concepto IN (59,60,61,62)
            AND movs.cve_tipo = 'P'
            AND just.proyecto IN( 'CANTARELL', 'EK BALAM', 'KU MALOOB ZAAP' )
          AND NOT EXISTS(SELECT 'x' FROM pron_just just2, pron_movs movs2 WHERE just2.id_justificacion = movs2.id_justificacion And just2.fecha_contable between TO_DATE(:FECHA_INI, 'DD/MM/YYYY') - 8 And TO_DATE(:FECHA_INI, 'DD/MM/YYYY') - 2 And just2.id_det_concepto = just.id_det_concepto And just2.proyecto = just.proyecto And movs2.cve_tipo = 'P' And movs2.id_instalacion = movs.id_instalacion)      
         GROUP BY DECODE(just.proyecto, 'EK BALAM', 'CANTARELL', just.proyecto), just.id_det_concepto
            
        UNION ALL
        
        SELECT
            DECODE(just.proyecto, 'EK BALAM', 'CANTARELL', just.proyecto) As activo,
            just.id_det_concepto, 
            COUNT(DISTINCT MOVS.ID_INSTALACION) As contador_pozos,
            'P' AS tipo
        FROM datawarezm.mne_ace_just_pos just, datawarezm.mne_ace_movs_pos movs
        WHERE just.id_just_pos = movs.id_just_pos
        AND just.fecha_contable + 1 BETWEEN 
                    TO_DATE(:FECHA_INI, 'DD/MM/YYYY') AND TO_DATE(:FECHA_FIN, 'DD/MM/YYYY')
        AND just.id_det_concepto IN (59,60,61,62)
        AND movs.cve_tipo = 'P'
        AND just.proyecto IN( 'CANTARELL', 'EK BALAM', 'KU MALOOB ZAAP' )
        AND NOT EXISTS(SELECT 'x' FROM pron_just just2, pron_movs movs2 WHERE just2.id_justificacion = movs2.id_justificacion And just2.fecha_contable between TO_DATE(:FECHA_INI, 'DD/MM/YYYY') - 8 And TO_DATE(:FECHA_INI, 'DD/MM/YYYY') - 2 And just2.id_det_concepto = just.id_det_concepto And just2.proyecto = just.proyecto And movs2.cve_tipo = 'P' And movs2.id_instalacion = movs.id_instalacion)      
       AND NOT EXISTS (SELECT 'x' FROM datawarezm.mne_ace_just_pos just2, datawarezm.mne_ace_movs_pos movs2 WHERE just2.id_just_pos = movs2.id_just_pos And just2.fecha_contable between TO_DATE(:FECHA_INI, 'DD/MM/YYYY') - 1 And TO_DATE(:FECHA_FIN, 'DD/MM/YYYY') - 1 And just2.id_det_concepto = just.id_det_concepto And movs2.cve_tipo = 'P' And movs2.id_instalacion = movs.id_instalacion  And just2.realizado='R')
        GROUP BY DECODE(just.proyecto, 'EK BALAM', 'CANTARELL', just.proyecto), just.id_det_concepto)
        GROUP BY ACTIVO,TIPO
        
        )))
    

       
       