SELECT
    'DATOS' As TIPO,
    DATOS_REAL.ID_EQUIPO, DATOS_REAL.PLATAFORMA, DATOS_REAL.EQUIPO,
    DATOS_REAL.FECHA_CONTABLE, DATOS_REAL.ESTADO, DATOS_REAL.T, DATOS_REAL.D,
    DATOS_REAL.REPARACION, DATOS_REAL.MANTENIMIENTO, NULL As INSTALADOS
FROM
    (SELECT
            DATOS.ID_EQUIPO, DATOS.PLATAFORMA, DATOS.EQUIPO, DATOS.FECHA_CONTABLE, DATOS.FECHA_REAL,
            XSIEDE.RMNE_SIEDE_VALOR_CAD(
                1128,
                TO_CHAR(DATOS.FECHA_REAL, 'DD/MM/YYYY'), 
                XSIEDE.DEVUELVEIDHORA(TO_CHAR(DATOS.FECHA_REAL, 'DD/MM/YYYY'), '05:00'),
                PLAT.ID_EXTERNO, PLAT.MODULO ) As ESTADO,
            DATOS.T,
            DATOS.D,
            NVL(DATOS.TEMC, 0) + NVL(DATOS.MC, 0) + NVL(DATOS.TEPPMC, 0) As REPARACION,
            NVL(DATOS.TEMP, 0) + NVL(DATOS.MP, 0) + NVL(DATOS.TEPPMP, 0) As MANTENIMIENTO
        FROM XSIEDE.RMN_SIE_TOTALES DATOS, XSIEDE.GAS_PLATAFORMAS_EQUIV_EXT PLAT
        WHERE DATOS.TIPO_INSTALACION = 'MODULOS'
            AND DATOS.FECHA_CONTABLE BETWEEN TO_DATE(:FECHAINI,'DD/MM/YYYY')-1 AND TO_DATE(:FECHAFIN, 'DD/MM/YYYY')-1
            AND DATOS.REGION = 'RMNE'
            AND ((DATOS.ACTIVO = 'CANTARELL') OR (DATOS.ACTIVO = 'GTDH' AND DATOS.PLATAFORMA = 'AKAL-C7'))
            AND PLAT.ID = DATOS.ID_EQUIPO) DATOS_REAL

UNION ALL

 SELECT 'TOTAL' As TIPO,
    NULL As ID_EQUIPO, NULL As PLATAFORMA, NULL As EQUIPO,
    FECHAS.FECHA_CONTABLE As FECHA_CONTABLE, NULL As ESTADO, NULL As T, NULL As D,
    NULL As REPARACION, NULL As MANTENIMIENTO, COUNT(GP_SIEDE.ID) As INSTALADOS
 FROM   XSIEDE.GAS_PLATAFORMAS GP_SIEDE,
           (SELECT TO_DATE(:FECHAINI, 'DD/MM/YYYY') + ROWNUM - 2 As FECHA_CONTABLE
             FROM DUAL
             CONNECT By ROWNUM <= ((TO_DATE(:FECHAFIN, 'DD/MM/YYYY') - TO_DATE(:FECHAINI, 'DD/MM/YYYY')) + 1)) FECHAS
WHERE GP_SIEDE.TIPO_INST = 'MODULOS'
   AND (GP_SIEDE.ACTIVO = 'CANTARELL' OR (GP_SIEDE.ACTIVO = 'GTDH' AND GP_SIEDE.PLATAFORMA = 'AKAL-C7'))
   AND GP_SIEDE.CATEGORIA = 'false'
   AND (GP_SIEDE.BAJA Is NULL Or FECHAS.FECHA_CONTABLE < GP_SIEDE.BAJA)
   AND (FECHAS.FECHA_CONTABLE >= GP_SIEDE.FEC_ALTA)
GROUP By FECHAS.FECHA_CONTABLE








SELECT
            DATOS.EQUIPO, DATOS.FECHA_CONTABLE as fecha,DATOS.T as tiempo
          
            
        FROM XSIEDE.RMN_SIE_TOTALES DATOS, XSIEDE.GAS_PLATAFORMAS_EQUIV_EXT PLAT
        WHERE DATOS.TIPO_INSTALACION = 'MODULOS'
            AND DATOS.FECHA_CONTABLE BETWEEN TO_DATE(:FECHAINI,'DD/MM/YYYY')-1 AND TO_DATE(:FECHAFIN, 'DD/MM/YYYY')-1
            AND DATOS.REGION = 'RMNE'
            AND ((DATOS.ACTIVO = 'CANTARELL') OR (DATOS.ACTIVO = 'GTDH' AND DATOS.PLATAFORMA = 'AKAL-C7'))
            AND DATOS.PLATAFORMA IN('AKAL-C4')
            AND PLAT.ID = DATOS.ID_EQUIPO
      
            
            
            
            
            
     SELECT DISTINCT
 PLATAFORMA
 FROM   XSIEDE.GAS_PLATAFORMAS GP_SIEDE,
           (SELECT TO_DATE(:FECHAINI, 'DD/MM/YYYY') + ROWNUM - 2 As FECHA_CONTABLE
             FROM DUAL
             CONNECT By ROWNUM <= ((TO_DATE(:FECHAFIN, 'DD/MM/YYYY') - TO_DATE(:FECHAINI, 'DD/MM/YYYY')) + 1)) FECHAS
WHERE GP_SIEDE.TIPO_INST = 'MODULOS'
   AND (GP_SIEDE.ACTIVO = 'CANTARELL' OR (GP_SIEDE.ACTIVO = 'GTDH' AND GP_SIEDE.PLATAFORMA = 'AKAL-C7'))
   AND GP_SIEDE.CATEGORIA = 'false'
   AND (GP_SIEDE.BAJA Is NULL Or FECHAS.FECHA_CONTABLE < GP_SIEDE.BAJA)
   AND (FECHAS.FECHA_CONTABLE >= GP_SIEDE.FEC_ALTA)







SELECT * FROM  XSIEDE.GAS_PLATAFORMAS





 SELECT DISTINCT
            DATOS.FECHA_CONTABLE as fecha
       
        FROM XSIEDE.RMN_SIE_TOTALES DATOS, XSIEDE.GAS_PLATAFORMAS_EQUIV_EXT PLAT
        WHERE DATOS.TIPO_INSTALACION = 'MODULOS'
            AND DATOS.FECHA_CONTABLE BETWEEN TO_DATE(:FECHAINI,'DD/MM/YYYY')-1 AND TO_DATE(:FECHAFIN, 'DD/MM/YYYY')-1
            AND DATOS.REGION = 'RMNE'
            AND ((DATOS.ACTIVO = 'CANTARELL') OR (DATOS.ACTIVO = 'GTDH' AND DATOS.PLATAFORMA = 'AKAL-C7'))
            AND DATOS.PLATAFORMA IN('AKAL-C4')
            AND PLAT.ID = DATOS.ID_EQUIPO
            
            
             (SELECT to_char(to_date(:FECHA_INI,'dd/mm/yyyy')-1 + ROWNUM - 1,'dd/MM/yyyy') As fecha  FROM DUAL 
               CONNECT By ROWNUM <= to_date(:FECHA_FIN,'dd/mm/yyyy') - to_date(:FECHA_INI,'dd/mm/yyyy') + 1 )